In [12]:
! pip install numpy
! pip install pandas
%pip install numpy
%pip install pandas

import numpy as np
import pandas as pd

Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.12/site-packages (1.26.4)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.12/site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in /Users/saishivanadhula/Library/Python/3.9/lib/python/site-packages (2.0.2)
WARNING: You are using pip version 21.2.4; however, version 25.0 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/saishivanadhula/Library/Python/3.9/lib/python/site-packages (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/saishivanadhula/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/saishivanadhula/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.1)
Requirement already satisfied: numpy>=1.22.4 in /Users/saishivanadhula/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/saishivanadhula/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
WARNING: You are using pip version 21.2.4; however, version 25.0 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [13]:
#reading the dataset
df=pd.read_csv("twitter_training.csv")

In [14]:
df.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...

In [15]:
%pip install nltk
import nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in /Users/saishivanadhula/Library/Python/3.9/lib/python/site-packages (3.9.1)
Requirement already satisfied: regex>=2021.8.3 in /Users/saishivanadhula/Library/Python/3.9/lib/python/site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /Users/saishivanadhula/Library/Python/3.9/lib/python/site-packages (from nltk) (4.67.1)
Requirement already satisfied: joblib in /Users/saishivanadhula/Library/Python/3.9/lib/python/site-packages (from nltk) (1.4.2)
Requirement already satisfied: click in /Users/saishivanadhula/Library/Python/3.9/lib/python/site-packages (from nltk) (8.1.8)
WARNING: You are using pip version 21.2.4; however, version 25.0 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [16]:
nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/saishivanadhula/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/saishivanadhula/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [17]:
from nltk.tokenize import word_tokenize

In [18]:
df.tail()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
74676,9200,Nvidia,Positive,Just realized that the Windows partition of my...
74677,9200,Nvidia,Positive,Just realized that my Mac window partition is ...
74678,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74679,9200,Nvidia,Positive,Just realized between the windows partition of...
74680,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...

In [19]:
x=df.iloc[0,1]
x

'Borderlands'

In [20]:
import re

In [22]:
if 'Text' in df.columns:
    df['Text'] = df['Text'].dropna()
    df['Text'] = df['Text'].astype(str)
else:
    print("Column 'Text' not found in DataFrame!")

Column 'Text' not found in DataFrame!

In [83]:
#data cleaning

# Remove special characters and punctuation using regex
mydata=[] #empty list
for i in df['Text']:
  text = re.sub(r',','',i)
  cleaned_text = re.sub(r'[^\w\s]', '', text)  # Removes everything except word characters and spaces
  cleaned_text = re.sub(r'\s+', ' ', cleaned_text)  # Replaces multiple spaces with a single space
  cleaned_data = cleaned_text.strip()  # Removes leading/trailing whitespace
  mydata.append(cleaned_data)

In [84]:
mydata

['Kickers on my watchlist XIDE TIT SOQ PNK CPW BPZ AJ trade method 1 or method 2 see prev posts',
 'user AAP MOVIE 55 return for the FEAGEED indicator just 15 trades for the year AWESOME',
 'user Id be afraid to short AMZN they are looking like a nearmonopoly in eBooks and infrastructureasaservice',
 'MNTA Over 1200',
 'OI Over 2137',
 'PGNX Over 304',
 'AAP user if so then the current downtrend will break Otherwise just a shortterm correction in medterm downtrend',
 'Mondays relative weakness NYX WIN TIE TAP ICE INT BMC AON C CHK BIIB',
 'GOOG ower trend line channel test volume support',
 'AAP will watch tomorrow for ONG entry',
 'im assuming FCX opens tomorrow above the 3425 trigger buy still very much like this setup',
 'It really worries me how everyone expects the market to rally nowusually exact opposite happens every time we shall see soon bac spx jpm',
 'AAP GAMCOs arry Haverty Apple Is Extremely Cheap Great Video',
 'user Maykiljil posted that I agree that MSFT is going higher possibly north of 30',
 'Momentum is coming back to ETFC Broke MA200 resistance on solid volume Friday ong setup',
 'HA Hitting 3565 means resume targeting 42 level',
 'user gameplan shot for today but I liked on trend break from May or ch break OC weekly trend break back to july 2011',
 'with FCX gapping well above ideal entry looking for a pull in to at least 35 on open for an entry',
 'user great list again particularly like FISV and SYK All buy hold types should check the free list out',
 'ATHX upper trend line',
 'NG nice PNF BY breakout need follow thru',
 'Wont believe AAP uptrend is back until it crosses above MA50',
 'X swing still on',
 'SWY 30 of float short and breaking out ouch',
 'BIOF wants 490s comin',
 'VS inverted head and shoulder play out well Wasnt able to catch the entry Eyes on it',
 'red not ready for break out',
 'EI close to breaking out now My trigger is at 3040',
 'user BAC For a quick Trade to lateBut for investing 1198 is a good entry point IMHO',
 'CHDN ong 4902 Trailing Stop 5666 from 6 prior Stops of 5417 4988 4982 4547 4302 4192',
 'AAP VOME today is impressive At this rate and well probably get to 30M shares traded today',
 'user been adding VXY long off the bottom today for trade also got WPI near low',
 'I repeat if global economy is going to get better this year go with C instead of BAC',
 'GOOG go ONG on close above 725',
 'NKD looking like a good short Failed to break price level resistance at 116 today',
 'GS like the price action So far holding above 130 Still deciding whether to go ONG calls or stocks',
 'SBX buy when it clears resistance at 545',
 'here is NEW up target for AAP and notice shakeout reading at 849 and we had buy dot Monday',
 'Too early to short into this move Stock Market needs a few days to settle down Patience COH BWD DT AAP PAY',
 'AAP obbers hit Apple Store in Paris Prefer to take merchendise over cash Bullish',
 'AXA Here is my tip of the day Buy now You do not even have to sign up for a newsletter or anything O If Im wrong I will eat crow',
 'X out the 12 due to the move today and the Kirby on the daily around 2600 still swinging 12',
 'AAP 10 min short won now longs have fully added in look for a pop here with marketshakeout reset',
 'NG stellar move still long swing full position I believe user user in it 2',
 'ATICE TADE SETP KO AN CNX',
 'IDCC 50SMA acting as a good support Shortterm momentum indicators have switched to the upside',
 'NEW POST BAC Is At 19 Month Highs But Showing Signs of Stress',
 'c two daily bull flags on top of each otherbullish still',
 'NG traditional and AT point and figure bullish BY signals multiyear high',
 'jpm closed10sma on Mondayu know my ruleslarge cup n handlestill bullish',
 'EOG ascending triangle original target 127 extension EPS Feb 11th 12 position swing',
 'aapl daily broke downtrendfrom closing prices now w v pattern back in play600 target',
 'PHM PulteGroup Option Bear bets 15 Million on 11 down move by April',
 'BAC In a 1197 for a trade',
 'Short Setups displaying relative weakness AO COH PAY BWD DT SHD WTW P Prepare to short the stall ES_F',
 'When AMZN monetize all electronics it makes with traffic to marketplace AAP GOOG will wake up and say why didnt we buy EBAY',
 'CVI starting with a clean book making first buy of the yr entry 4954 stop 4743',
 'SAM cheers to the temporary solution to our economic woes entry 13981 stop 13192',
 'SK to the GAVE',
 'ovti ttm ending Oct 2012 Negative 151 million operational cash flow 273 decline vs yoy ttm ending oct 2011',
 'AAP and GOOG should respond positively to good jobless claims numbers',
 'Analyst price targets and earnings targets coming downEXACTY what you want to see prior AAP reporting',
 'user Nice Color me an INTC bull as well',
 'Heads p AA Earnings 1813 ess Than a Week Away Tho The Season Doesnt EAY Begin Cranking Til 116 w GS JPM EBAY et al',
 'trade idea buy WO market 2664 target 36 cut below 2350',
 'Trade idea buy DC market 5850 target 67 cut below 53',
 'GOOG looks all set to make new ATH Now before or after E is the unknown',
 'GOOG trade this one long verse 10sma',
 'FNF ong 1943 Trailing Stop 2104 from 6 prior Stops of 1971 1952 1870 1865 1807 and 1787',
 'FOD should see a solid move up tom system predict nice green candle',
 'This is the year of fitness and health appsthe winners will be gynormous and the speculation will run high nke',
 'Its time to invest in MSFT COMPQ',
 'New Post Shorts Will Make Dimes ongs Will Make Dollars AAP SPX QQQ P',
 'nbelieveable payment trend that VCs are chasing has easily played out in public markets EBAY V and Mastercard MA all time highs',
 'Some of the watch list stocks that triggered today OEX AGNX TV VBD XIDE PPC EXP ONTY BMN FS WK CHMT FBC ISI AIG',
 'Nice Bull flag breakout here OC technology software',
 'My setup alerts went bonkers todayOne of many that got triggeredCupHandle breakout in PFE',
 'The host with the mostcongrats to the cloud today AX and user more alltime highs wow',
 'X Did S Steel Just Breakout MT too',
 'DNDN has broken through the clear 55 resistanc level on heavy volume could be headed much higher',
 'EXPE looks good for higher prices',
 'apc weekly setting up long',
 'I am going into this morning long 3 each AAP 560 call options GOOG 725 calls Jan 4th expiration',
 'ES_F path higher unthreatened unless 145225 support fails See resistance at 146600 SPX stocks',
 'Monitor the S lineprice dynamic Stocks that closed Dec28 with the S line in new highs be4 price MHO TSM IPGP EQIX BC BDC ASH',
 'DDD IDCC continue higher',
 'Had hoped to pick up some OST today but looks like Im a day too late Nice move up this morning',
 'GPS wow that wa s a fast fast fade',
 'AMZN going above 260 Should go near 300 if market behaves for a few weeks',
 'Huston we have a GEEN AAP',
 'P long 955',
 'HN breakoutbut 3rd day up so look for pullback to enter long',
 'NG ascend triangle much like FS X breakouts 127 exten then 1618 targets fibs subjective',
 'KCG things that make you go hmmmm',
 'VNG Huge news from patent attorney Dan avicher',
 'NG nhod check the weekly target previous lows 2006',
 'NG nhod what do you see check the weekly target previous lows 2006',
 'AIG American International Group Option Traders bet on 4 down move by next Friday',
 'P out balance 32',
 'VNG buys vs Sells',
 'BAC In 1200 since there is consolidation this level We could close 1209 if market is stable in pm IMHO',
 'VNG Parabolic moves are a comin',
 'New Sony preowned block tech patent unearthed SNE 50 of GME profits from pre owned last one out turn off the lights',
 'we liked VS we love WYNN from 111 entry to new up target yesterday at 121 very nice',
 'user SPX 146490 Wave iv would be 20 points lower 146700 KEY ES_F HOD 146000 under neckline 145850 very bearish',
 'DDD consolidating the strong move from previous days between 55 and 60 next buy point above 60 on volume holding',
 'VNG 12 mil shares shorts plus long buying massive VNG short squeeze Just when you thought story was dead avicher kills short thesis',
 'Wow not good for BKS T user sales for the Nook were down 13 over the holidays',
 'AC from watch list volume did pick up and is now 139 of full day average from 200day bounce',
 'The new wightwatchers ads are more fun and light and with regular people more interesting but I still dont trust them WTW no position',
 'AMZN holding up well next buy point when clears this upper trend line on heavy volume',
 'MA exactly what you want to see a follow thru day after breaking out to new highs on volume',
 'ZCS user Theres your buying',
 'AAP SPY no more QE for 2013 Now bring the Geithner',
 'Over extended stock market unexpected news from the FED minutes Down ESD a panicky ES_F NQ_F',
 'SPY ncle Ben needed to spice up things a little AAP people were bored wake up now',
 'AAP might close at the lows of the day Bears will be in control again below the descending trendline Watch it',
 'FAN seeking 200d Im adding some synthetic shorts here and will add again at 200d',
 'CWST low of day 450 near high of day 456 watchn for bout minimal risk',
 'All of the above gme Gamestop short targets spy',
 'time to get out of the cloud stocks VMW CM',
 'BAC Keep Overniight mmy pos will bin premarket Tmorrow too',
 'Polk Expects 2013 S New Vehicle egistrations to each 153 Million Polk F GM I think this is low',
 'Very bullish on market also talked trends for SCTY OST ANGI FIO PANW A JCP P YEP MNST GPN on show',
 'BAC what happens next',
 'KCG someone bought 322k 4 Jan 18 Calls',
 'Man I didnt know about Skippy when I made thiswould have thrown in a jar H Hormel',
 'Big move in bonds today 7 months high for 10 y rate still going lower here ZN_F could get truly ugly if good NFP number in AM SPY TT',
 'Market Wrap Video Additions to Watch ist including BCEI BJI CEE ES SONS SQNM NX YEP',
 'Maybe when vrng asked the judge for a 7 royalty it became too risky for goog to deal with they want to settle',
 'BJI Over 3553 if good volume',
 'CEE Over 3512',
 'SQNM Over 505',
 'NX On flag break',
 '3D Systems Brings NextGen Consumer 3D Printing to CES 2013 DDD',
 'AAP will top out in April when Aston Kutcher stars in jOBS Kinda like how Facebook did when Social Network came out FB',
 'VNG w MACD turning up above its signal line VNG could post a nice rally from current levels',
 'PI 3Q 10Q operational cash flow for 9mos 20million 269decline vs 9mos year ago',
 'bbby 3Q 10Q Operational Cash Flow 135 million 53 increase vs year ago Q3 64 improvement q o q',
 'DI 6mos operational cash flow 267 million increases 187 million vs6mos year ago 233 increase',
 'AM 3Q 10Q 9mos operational cash flow 32 million vs neg 26 mil 9mos year ago',
 'am 3Q operational cash flow neg 16 million vs year ago 3Q of negative 68million 52 million improvement',
 'A quiet Carl Icahn Bullish NFX shorts should be paranoid on every close as they will get acquired Think aapl msft amzn fb',
 'I am an aapl bull but cannot break this trend line in OBV',
 'user Phantom7 Ive been calling 4 ever since the start of this thing 375 should be a given KCG',
 'NX on watch list above small flag on volume of 26 of ave full day so good volume',
 'GOOG poised to clear this next resistance buy add area watch action volume closely here',
 'GDP on watch list slightly over line and 50day EMA light volume of 5 ave full day',
 'Took some profits off DDD will add if breaks 60 on volume',
 'CHK what Im looking at small risk position calls only Scalp maybe a swing XE watch',
 'ONTY If the holders would just hold out or raise their ask here this could really pop Going to climb slowly regardless',
 'EOG PXD OAS energyswag',
 'AAP moving down with volume Couldnt cope with the descending trend line Trend is still down Perhaps 460 is not impossible after all',
 'AAP 50EMA continue to work as AAP is making lower highs in the MACO sense',
 'Went short SPY yesterday should have picked AAP instead Still think market needs to move down a bit then resume move to the upside',
 'AAP people be realistic Market undecided what to do with apple Earnings will lift that cloud If GOOD we might EAY see a reversal',
 'Will watch the close carefully then decide whether to ONG or SHOT AAP Below 530 SHOT',
 'JCP Keep an eye on this triangle big short int 34 reports Feb 27 cup handle at DT ong',
 'sold a little goog first time in a while',
 'Nice cup with handle breakout on MCA',
 'FAF new highs',
 'SPY giving AAP the finger We dont care about you anymore lol',
 'The SmithCorona doing ok AMZN',
 'VA ong 4307 Trailing Stop 5898 from 11 Stops of 5453 5245 4805 4732 4671 4132 3957',
 'AMZN alert update a last minute push tried to shake out puts were hanging on for now',
 'AAP volume higher today than monday Keep that in mind',
 'HBA ong 7367 Trailing Stop 7192 from 3 prior Stops of 7086 6864 and 6241',
 'The key is not to panic here AAP is in the domain of twitchy day traders on robots now but long term should hold up on fundamentals',
 'NVDA 4 hour love to see the vol explode',
 'VNG Take a hard look at GOOG FTC settlement over patents FTC making GOOG play nice with VNG Makes Sense',
 'some worried I had gone OCO with my 73771 up call for GOOG now at door step of nearly 40 move',
 'VNG its crazy that anyone listens and trades off this tool',
 'GOOG is getting fueled by AAPs reversal',
 'user why make a BBY offer now when he can shave 4 more off offer price Bid went from 2426 to just 20 in a matter of months',
 'NVDA to answer your question entry add was the red candle at 1050AM today ove flags',
 'AAP 950 lot bid in the Feb 580 call at 950 might push the stock up or create support 26 delta option',
 'WPI was on our short candidate list 1231 and we missed it got started short today',
 'MYE breaking out',
 'Short HT under the 200 SMA stop just over the high of the day First target 5395 Second target 5321 gap fill',
 'QCOM introduces StreamBoost average home connects up to seven devices to the Internet',
 'NVDA love to see momo this next week like previous histogram bars noted',
 'HMA unusual option activity Trader buys 11k of the Jan 9 Put Short term bear play',
 'ADBE option trader buys 5300 of the Feb 39C against OI of 741 Bet is on stock above 39 by Feb 16th',
 'NVDA ooks bullish but it must stay above 1305 on a closing basis monthly EPS say no',
 'SQNM from watch list over line on volume of 86 of ave full day',
 'HOTT Failed breakout',
 'ZN_F ticking up Id be a seller of SDJPY here if I werent already',
 'INO Wow nice accumulation today heavy',
 'ZNGA Fat juicy Short back to lower levels as it closes Gap 272',
 'GDOT nice bounce from its 50SMA ooks ready to test the recent highs',
 'HMA ooking for 10s headed higher',
 'SPF ooking for 9s headed higher with lower rates',
 'GS JPM XF HOD they are hungry for stocks out there SPY',
 'CHK weekly bullish engulfing',
 'GS looks good heading into next week',
 'AAP all i know is ipad minis are out of stock everywhere been going to 8 different stores and none of them have em in stock',
 'As goog explodes and aapl implodes MINTE 21 to 23 of user vid from a few years ago have Mark nailing the subject',
 'KKD Krispy Kreme Doughnuts Inc at IC XChange Conference ive 011713 at 915 am ET',
 'Picked up FS on pullback due to downgrade Held support to close week First PT 3730',
 'user Ive been picking this one for a while but Im calling KKD as the next food company to make a DPZ like run in TWENTY13',
 'ZNGA Still shows red and dead on a enko view PF Box size 025',
 'GS enko view of GS PF Box size 5 showing potential to break to 175',
 'NVDA enko view showing red and dead need 14 or more for a long less than 13 for a short',
 'CSX enko view PF Box size 1 VEY bullish above 21 coal stocks confirming move on rails',
 'GOOG And on enko w a PF Box size of 50 it looks like a failed breakout',
 'user At 155 for GS but very bullish on fins as rates are low The FED Put',
 'user ZNGA I use lagging indicators on lagging stocks',
 'GOOG I like it with a close above 74496',
 'FS bo above bull flag on heavy vol etest of support today on light vol 41 short float',
 'MSFT gap close Continues base SI rising Nice pickup w stop below major support 2822 PT',
 'Financials continue ripping Easy money C approaching 43 PT',
 'VS follow throughs 10 DMA crossing above 200 DMA Trading above all MAs Great setup',
 'user BAC Yeah they made the easy profits by slashing jobs now they have to close winwin sales',
 'New buys today from watch list all did well NX 20 SONS YEP BCEI GDP AY and SQNM Total triggers this week 39 a big week',
 'SBX SI EarthThis is the kind of stuff that makes us perk up so sorrybut go onbullish five waves to 58',
 'Can you say no brainier ong SBAC stock 6080 Feb collar for protection',
 'Anyone can say how much svu would go even if the deal goes through 4 5 Not sure if much upside left',
 'NVDA the bounce continues and the stock has now cleared its 200SMA and the 13 level ong',
 'AXTI Momentum picking up w MACD climbingSI risingOBV indicator made a new higher high this week',
 'GDOT OBV is moving upwards which means that big money is moving into the stock slowly ong',
 'aapl daily see notes',
 'AMZN daily see notes',
 'C daily see notes',
 'EGOV long 1662 strong above all MAs restingbasing room to upper bolly to absorb 1020 day atr',
 'AA Fibs Friends',
 'TSA Judge Dismisses Massachusetts State Automobile Dealers Association awsuit',
 'BAC up trending doesnt appear to slow down as of yet Its prudent to take some profit at time',
 'FE looks like it fired a sell signal Friday may trade this short on tick below Friday low have to do more work on utilities later',
 'coh also got rejected by cloud but still in slight uptrend for past few buy when it enters cloud',
 'yum looks good here out of cloud with stops of either 200 sma or cloud under it target of 50 sma',
 'EQIX EXPE FB GS HOG MON PII QCOM QIH SODA Some ideas for next week Favorite setup is EQIX',
 'EQIX No position would like to see a breakout over 21650 Prefer more consolidation though',
 'Time for a contraction in AAPdown to test 500 this week by Wedslong Jan11th 510500 put spread',
 'AAP Bounce Coming',
 'FS en fuego',
 'AXA OverSold in Oscillating angeindicators suggest buy price holds above prev close increase in volume',
 'A few Im not holding but will check out user Bullish MACD cross BBG COP ENI EOG JEC IG SFY XE XOP',
 'JDS beautiful trend 135 should bring out the dip buyers',
 'ko has trouble staying above 200 day sma past few weeks could short here or higher stops above 38',
 'mako a red day monday breaks support and could test old lows of 9925',
 'Afterhour Most Advanced OPT MAKO FOD GNMK JDS EGE AMN PX AAY DDD SV PM BKS F',
 'GOOG with simple Fibonacci projections on close over 739 1272 at 766 and 1618 at 802',
 'Why I am buying AAP on Monday',
 'user AMZN over 263 has a Measured Move to 307',
 'user The INO pipeline and the partnerships with the nis and MKthat pretty much sums it up',
 'AMZN the data company not the retailer A new post by me',
 'Trading environment favors long side Dont over stay welcome Too few quality leaders GS AMH OCN EGN HOV AAP',
 'AAP what an amazing run it has been since 2005 I dont think its over',
 'A Tale of Two Stocks AAP GOOG SPY QQQ',
 'F Fords Powerful Bullish Pattern Dictates Price Direction',
 'DT Descending triangle ower highs Didnt participate well in the rally its overbought',
 'CVA Over 1900',
 'MCK Over 10005',
 'VMED you know we prefer 34 day pullback to reverse so maybe Mon or Tuesday on flag break or at sup',
 'Just kidding more legible version Currently long FS tweeted on friday',
 'Ford will perform well due to Hurricane Sandys destruction F Palladium will do well PA Banks are a buy picks are BAC C SAN GS',
 'GS is a buy on pullback to 133 or on bigger pullback to 130',
 'CEG keep it on you watch list',
 'I wish TV would die already like all the Newspapers told me CBS ftw',
 'I think AAP is heading back down to check in on 506 support again',
 'AMZN but but butyap yap yap',

In [85]:
tokens=[word_tokenize(x) for x in df['Text']]

In [86]:
tokens[5]

['PGNX', 'Over', '3.04']

In [87]:
#to remove stop words
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mehna\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [88]:
stop=stopwords.words('english')

In [89]:
stop_token=[]
for x in tokens:
  cl = [i for i in x if i not in stop]
  stop_token.append(cl)

In [90]:
stop_token

[['Kickers',
  'watchlist',
  'XIDE',
  'TIT',
  'SOQ',
  'PNK',
  'CPW',
  'BPZ',
  'AJ',
  'trade',
  'method',
  '1',
  'method',
  '2',
  ',',
  'see',
  'prev',
  'posts'],
 ['user',
  ':',
  'AAP',
  'MOVIE',
  '.',
  '55',
  '%',
  'return',
  'FEA/GEED',
  'indicator',
  '15',
  'trades',
  'year',
  '.',
  'AWESOME',
  '.'],
 ['user',
  'I',
  "'d",
  'afraid',
  'short',
  'AMZN',
  '-',
  'looking',
  'like',
  'near-monopoly',
  'eBooks',
  'infrastructure-as-a-service'],
 ['MNTA', 'Over', '12.00'],
 ['OI', 'Over', '21.37'],
 ['PGNX', 'Over', '3.04'],
 ['AAP',
  '-',
  'user',
  'current',
  'downtrend',
  'break',
  '.',
  'Otherwise',
  'short-term',
  'correction',
  'med-term',
  'downtrend',
  '.'],
 ['Monday',
  "'s",
  'relative',
  'weakness',
  '.',
  'NYX',
  'WIN',
  'TIE',
  'TAP',
  'ICE',
  'INT',
  'BMC',
  'AON',
  'C',
  'CHK',
  'BIIB'],
 ['GOOG',
  '-',
  'ower',
  'trend',
  'line',
  'channel',
  'test',
  '&',
  'volume',
  'support',
  '.'],
 ['AAP', 'watch', 'tomorrow', 'ONG', 'entry', '.'],
 ["'m",
  'assuming',
  'FCX',
  'opens',
  'tomorrow',
  '34.25',
  'trigger',
  'buy',
  '.',
  'still',
  'much',
  'like',
  'setup',
  '.'],
 ['It',
  'really',
  'worries',
  'everyone',
  'expects',
  'market',
  'rally',
  ',',
  'usually',
  'exact',
  'opposite',
  'happens',
  'every',
  'time',
  'shall',
  'see',
  'soon',
  'bac',
  'spx',
  'jpm'],
 ['AAP',
  'GAMCO',
  "'s",
  'arry',
  'Haverty',
  ':',
  'Apple',
  'Is',
  'Extremely',
  'Cheap',
  'Great',
  'Video',
  '!',
  '!',
  '!'],
 ['user',
  'Maykiljil',
  'posted',
  '.',
  'I',
  'agree',
  'MSFT',
  'going',
  'higher',
  '&',
  'possibly',
  'north',
  '30'],
 ['Momentum',
  'coming',
  'back',
  'ETFC',
  'Broke',
  'MA200',
  'resistance',
  'solid',
  'volume',
  'Friday',
  '.',
  'ong',
  'set-up'],
 ['HA',
  'Hitting',
  '35.65',
  'means',
  'resume',
  'targeting',
  '42',
  'level',
  '..'],
 ['user',
  'gameplan',
  'shot',
  'today',
  'I',
  'liked',
  'trend',
  'break',
  'May',
  'c+h',
  'break',
  '.',
  'OC',
  'weekly',
  'trend',
  'break',
  'back',
  'july',
  '2011'],
 ['FCX',
  'gapping',
  'well',
  'ideal',
  'entry',
  'looking',
  'pull',
  'least',
  '35',
  'open',
  'entry'],
 ['user',
  'great',
  'list',
  ',',
  'particularly',
  'like',
  'FISV',
  'SYK',
  '.',
  'All',
  'buy',
  '&',
  'hold',
  'types',
  'check',
  'free',
  'list',
  '.'],
 ['ATHX', 'upper', 'trend', 'line'],
 ['NG',
  '-',
  'nice',
  'PNF',
  'BY',
  '-',
  'breakout',
  '-',
  'need',
  'follow',
  'thru'],
 ['Wo',
  "n't",
  'believe',
  'AAP',
  'uptrend',
  'back',
  'crosses',
  'MA',
  '(',
  '50',
  ')'],
 ['X', 'swing', 'still'],
 ['SWY', '-', '30', '%', 'float', 'short', 'breaking', '-', 'ouch'],
 ['BIOF', 'wants', '4.90', "'s", 'comin', '!', '!', '!'],
 ['VS',
  'inverted',
  'head',
  'shoulder',
  'play',
  'well',
  '.',
  'Was',
  "n't",
  'able',
  'catch',
  'entry',
  '.',
  'Eyes'],
 ['red', ',', 'ready', 'break', '.'],
 ['EI', 'close', 'breaking', '.', 'My', 'trigger', '30.40', '.'],
 ['user',
  'BAC',
  'For',
  'quick',
  'Trade',
  'late',
  '..',
  'But',
  'investing',
  '~11.98',
  'good',
  'entry',
  'point',
  'IMHO'],
 ['CHDN',
  '-',
  'ong',
  '49.02',
  '.',
  'Trailing',
  'Stop',
  '56.66',
  '6',
  'prior',
  'Stops',
  '54.17',
  ',',
  '49.88',
  ',',
  '49.82',
  ',',
  '45.47',
  ',',
  '43.02',
  '&',
  '41.92',
  '-'],
 ['AAP',
  'VOME',
  'today',
  'impressive',
  '.',
  'At',
  'rate',
  'well',
  'probably',
  'get',
  '30M',
  'shares',
  'traded',
  'today',
  '.'],
 ['user',
  ':',
  'adding',
  'VXY',
  'long',
  'bottom',
  'today',
  'trade',
  ',',
  'also',
  'got',
  'WPI',
  'near',
  'low'],
 ['I',
  'repeat',
  ',',
  'global',
  'economy',
  'going',
  'get',
  'better',
  'year',
  'go',
  'C',
  'instead',
  'BAC'],
 ['GOOG', 'go', 'ONG', 'close', '725', '.'],
 ['NKD',
  'looking',
  'like',
  'good',
  'short',
  '.',
  'Failed',
  'break',
  'price',
  'level',
  'resistance',
  '116',
  'today',
  '.'],
 ['GS',
  'like',
  'price',
  'action',
  '.',
  'So',
  'far',
  'holding',
  '130',
  '.',
  'Still',
  'deciding',
  'whether',
  'go',
  'ONG',
  'calls',
  'stocks',
  '.'],
 ['SBX', 'buy', 'clears', 'resistance', '54.5'],
 ['NEW',
  'target',
  'AAP',
  'notice',
  'shakeout',
  'reading',
  '-8.49',
  '!',
  'buy',
  'dot',
  'Monday'],
 ['Too',
  'early',
  'short',
  'move',
  '.',
  'Stock',
  'Market',
  'needs',
  'days',
  'settle',
  '.',
  '#',
  'Patience',
  'COH',
  'BWD',
  'DT',
  'AAP',
  'PAY'],
 ['AAP',
  'obbers',
  'hit',
  'Apple',
  'Store',
  'Paris',
  '.',
  'Prefer',
  'take',
  'merchendise',
  'cash',
  '.',
  'Bullish',
  '.'],
 ['AXA',
  'Here',
  'tip',
  'day',
  '.',
  'Buy',
  '!',
  'You',
  'even',
  'sign',
  'newsletter',
  'anything',
  'O',
  'If',
  'I',
  "'m",
  'wrong',
  'I',
  'eat',
  'crow',
  ':',
  ')'],
 ['X',
  '1/2',
  'due',
  'move',
  'today',
  'Kirby',
  'daily',
  'around',
  '26.00',
  '-',
  'still',
  'swinging',
  '1/2'],
 ['AAP',
  '10',
  'min',
  'short',
  'longs',
  'fully',
  'added',
  ',',
  'look',
  'pop',
  'market',
  ',',
  'shakeout',
  'reset'],
 ['NG',
  'stellar',
  'move',
  '-',
  'still',
  'long',
  'swing',
  '-',
  'full',
  'position',
  '-',
  'I',
  'believe',
  'user',
  '&',
  'user',
  '2'],
 ['ATICE', '&', 'TADE', 'SETP', ':', 'KO', 'AN', 'CNX'],
 ['IDCC',
  '50SMA',
  'acting',
  'good',
  'support',
  '.',
  'Short-term',
  'momentum',
  'indicators',
  'switched',
  'upside',
  '.'],
 ['NEW',
  'POST',
  ':',
  'BAC',
  'Is',
  'At',
  '19',
  'Month',
  'Highs',
  ',',
  'But',
  'Showing',
  'Signs',
  'Stress'],
 ['c', 'two', 'daily', 'bull', 'flags', 'top', 'other=bullish', 'still'],
 ['NG',
  '-',
  'traditional',
  'AT',
  'point',
  'figure',
  '-',
  'bullish',
  'BY',
  'signals',
  'multiyear',
  'high'],
 ['jpm',
  'closed',
  '>',
  '10sma',
  'Monday',
  '(',
  'u',
  'know',
  'rules',
  ')',
  '...',
  'large',
  'cup',
  'n',
  'handle',
  '....',
  'still',
  'bullish'],
 ['EOG',
  'ascending',
  'triangle',
  '-',
  'original',
  'target',
  '127',
  'extension',
  'EPS',
  'Feb',
  '11th',
  '?',
  '1/2',
  'position',
  'swing'],
 ['aapl',
  'daily',
  ',',
  'broke',
  'downtrend',
  '(',
  'closing',
  'prices',
  ')',
  'w',
  'v',
  'pattern',
  'back',
  'play',
  '.......',
  '600',
  'target'],
 ['PHM',
  'PulteGroup',
  'Option',
  'Bear',
  'bets',
  '1.5',
  'Million',
  '11',
  '%',
  'move',
  'April'],
 ['BAC', 'In', '11.97', 'trade'],
 ['Short',
  'Setups',
  'displaying',
  'relative',
  'weakness',
  ':',
  'AO',
  'COH',
  'PAY',
  'BWD',
  'DT',
  'SHD',
  'WTW',
  'P',
  'Prepare',
  'short',
  'stall',
  '.',
  'ES_F'],
 ['When',
  'AMZN',
  'monetize',
  'electronics',
  'makes',
  'traffic',
  'marketplace',
  ',',
  'AAP',
  'GOOG',
  'wake',
  'say',
  "n't",
  'buy',
  'EBAY'],
 ['CVI',
  'starting',
  'clean',
  'book',
  ',',
  'making',
  'first',
  'buy',
  'yr',
  '-',
  'entry',
  '49.54',
  'stop',
  '47.43'],
 ['SAM',
  'cheers',
  'temporary',
  'solution',
  'economic',
  'woes',
  '-',
  'entry',
  '139.81',
  'stop',
  '131.92'],
 ['SK', 'GAVE', '!'],
 ['ovti',
  'ttm',
  'ending',
  'Oct',
  '2012',
  'Negative',
  '151',
  'million',
  'operational',
  'cash',
  'flow',
  '..',
  '273',
  '%',
  'decline',
  'vs',
  'yoy',
  'ttm',
  'ending',
  'oct',
  '2011'],
 ['AAP',
  'GOOG',
  'respond',
  'positively',
  'good',
  'jobless',
  'claims',
  'numbers'],
 ['Analyst',
  'price',
  'targets',
  'earnings',
  'targets',
  'coming',
  '--',
  '-EXACTY',
  'want',
  'see',
  'prior',
  'AAP',
  'reporting',
  '.'],
 ['user', 'Nice', '!', 'Color', 'INTC', 'bull', 'well', '!'],
 ['Heads',
  'p',
  ':',
  'AA',
  'Earnings',
  '(',
  '1/8/13',
  ')',
  'ess',
  'Than',
  'Week',
  'Away',
  ',',
  'Tho',
  'The',
  'Season',
  'Does',
  "n't",
  'EAY',
  'Begin',
  'Cranking',
  "'Til",
  '1/16',
  'w/',
  'GS',
  'JPM',
  'EBAY',
  'et',
  'al',
  '...'],
 ['trade',
  'idea',
  'buy',
  'WO',
  'market',
  '26.64',
  ',',
  'target',
  '36',
  ',',
  'cut',
  '23.50'],
 ['Trade',
  'idea',
  'buy',
  'DC',
  'market',
  '58.50',
  ',',
  'target',
  '67',
  ',',
  'cut',
  '53'],
 ['GOOG',
  'looks',
  'set',
  'make',
  'new',
  'ATH',
  '.',
  'Now',
  'E',
  'unknown',
  '.'],
 ['GOOG', 'trade', 'one', 'long', 'verse', '10sma'],
 ['FNF',
  '-',
  'ong',
  '19.43',
  '.',
  'Trailing',
  'Stop',
  '21.04',
  '6',
  'prior',
  'Stops',
  '19.71',
  ',',
  '19.52',
  ',',
  '18.70',
  ',',
  '18.65',
  ',',
  '18.07',
  '17.87',
  '-'],
 ['FOD',
  'see',
  'solid',
  'move',
  'tom',
  ',',
  'system',
  'predict',
  'nice',
  'green',
  'candle',
  '.'],
 ['This',
  'year',
  'fitness',
  'health',
  'apps',
  '...',
  'winners',
  'gynormous',
  'speculation',
  'run',
  'high',
  'nke'],
 ['It', "'s", 'time', 'invest', 'MSFT', 'COMPQ'],
 ['New',
  'Post',
  ':',
  'Shorts',
  'Will',
  'Make',
  'Dimes',
  ',',
  'ongs',
  'Will',
  'Make',
  'Dollars',
  'AAP',
  'SPX',
  'QQQ',
  'P'],
 ['nbelieveable',
  'payment',
  'trend',
  'VC',
  "'s",
  'chasing',
  'easily',
  'played',
  'public',
  'markets',
  '....',
  'EBAY',
  'V',
  'Mastercard',
  'MA',
  'time',
  'highs'],
 ['Some',
  'watch',
  'list',
  'stocks',
  'triggered',
  'today',
  'OEX',
  'AGNX',
  'TV',
  'VBD',
  'XIDE',
  'PPC',
  'EXP',
  'ONTY',
  'BMN',
  'FS',
  'WK',
  'CHMT',
  'FBC',
  'ISI',
  'AIG'],
 ['Nice',
  'Bull',
  'flag',
  'breakout',
  'OC',
  '#',
  'technology',
  '#',
  'software'],
 ['My',
  'setup',
  'alerts',
  'went',
  'bonkers',
  'today',
  '..',
  'One',
  'many',
  'got',
  'triggered.Cup+Handle',
  'breakout',
  'PFE'],
 ['The',
  'host',
  '....',
  'congrats',
  'cloud',
  'today',
  'AX',
  'user',
  'all-time',
  'highs',
  '.',
  'wow'],
 ['X', 'Did', '.S', '.', 'Steel', 'Just', 'Breakout', '?', 'MT'],
 ['DNDN',
  'broken',
  'clear',
  '5.5',
  'resistanc',
  'level',
  'heavy',
  'volume',
  '&',
  'could',
  'headed',
  'much',
  'higher'],
 ['EXPE', 'looks', 'good', 'higher', 'prices'],
 ['apc', 'weekly', 'setting', 'long', '.'],
 ['I',
  'going',
  'morning',
  'long',
  '3',
  'AAP',
  '560',
  'call',
  'options',
  '&',
  'GOOG',
  '725',
  'calls',
  'Jan',
  '4th',
  'expiration'],
 ['ES_F',
  'path',
  'higher',
  'unthreatened',
  'unless',
  '1452.25',
  'support',
  'fails',
  '.',
  'See',
  'resistance',
  '1466.00',
  'SPX',
  '#',
  'stocks',
  '.'],
 ['Monitor',
  'S',
  'line/price',
  'dynamic',
  '.',
  'Stocks',
  'closed',
  'Dec.28',
  'S',
  'line',
  'new',
  'highs',
  'be4',
  'price',
  '.',
  'MHO',
  'TSM',
  'IPGP',
  'EQIX',
  'BC',
  'BDC',
  'ASH'],
 ['DDD', 'IDCC', 'continue', 'higher'],
 ['Had',
  'hoped',
  'pick',
  'OST',
  'today',
  ',',
  'looks',
  'like',
  'I',
  "'m",
  'day',
  'late',
  '.',
  'Nice',
  'move',
  'morning',
  '.'],
 ['GPS', 'wow', 'wa', 'fast', 'fast', 'fade', '...'],
 ['AMZN',
  'going',
  '260',
  '.',
  'Should',
  'go',
  'near',
  '300',
  'market',
  'behaves',
  'weeks',
  '.'],
 ['Huston', 'GEEN', 'AAP'],
 ['P', 'long', '9.55'],
 ['HN',
  'breakout',
  '...',
  '3rd',
  'day',
  'look',
  'pullback',
  'enter',
  'long',
  '.'],
 ['NG',
  '-',
  'ascend',
  'triangle',
  'much',
  'like',
  'FS',
  '&',
  'X',
  'breakouts',
  '127',
  'exten',
  '161.8',
  'targets',
  '-',
  'fibs',
  'subjective'],
 ['KCG', '...', 'things', 'make', 'go', 'hmmmm', '?'],
 ['VNG', '-', 'Huge', 'news', 'patent', 'attorney', 'Dan', 'avicher'],
 ['NG',
  'nhod',
  '-',
  'check',
  'weekly',
  '-',
  'target',
  'previous',
  'lows',
  '2006',
  ':',
  ')'],
 ['NG',
  'nhod',
  '-',
  'see',
  '?',
  'check',
  'weekly',
  '-',
  'target',
  'previous',
  'lows',
  '2006',
  ':',
  ')'],
 ['AIG',
  'American',
  'International',
  'Group',
  'Option',
  'Traders',
  'bet',
  '4',
  '%',
  'move',
  'next',
  'Friday'],
 ['P', 'balance', '+.32'],
 ['VNG', 'buys', 'vs.', 'Sells', '?'],
 ['BAC',
  'In',
  '12.00',
  'since',
  'consolidation',
  'level',
  '.',
  'We',
  'could',
  'close',
  '=',
  '>',
  '12.09',
  'market',
  'stable',
  'pm',
  'IMHO',
  '.'],
 ['VNG', 'Parabolic', 'moves', 'comin', "'"],
 ['New',
  'Sony',
  'pre-owned',
  'block',
  'tech',
  'patent',
  'unearthed',
  'SNE',
  '...',
  '50',
  '%',
  'GME',
  'profits',
  'pre',
  'owned',
  '..',
  'last',
  'one',
  'turn',
  'lights'],
 ['liked',
  'VS',
  ',',
  'love',
  'WYNN',
  '111',
  'entry',
  'new',
  'target',
  'yesterday',
  '121.',
  'nice',
  '!'],
 ['user',
  ':',
  'SPX',
  '1464.90',
  'Wave',
  'iv',
  'would',
  '20',
  'points',
  'lower',
  '[',
  '1467.00',
  'KEY',
  ']',
  'ES_F',
  'HOD',
  '1460.00',
  '(',
  'neckline',
  '1458.50',
  'bearish',
  ')'],
 ['DDD',
  'consolidating',
  'strong',
  'move',
  'previous',
  'days',
  '55',
  '60',
  ',',
  'next',
  'buy',
  'point',
  '60',
  'volume',
  '(',
  'holding',
  ')',
  '.'],
 ['VNG',
  '-',
  '12',
  'mil',
  'shares',
  'shorts',
  'plus',
  'long',
  'buying',
  '=',
  'massive',
  'VNG',
  'short',
  'squeeze',
  '.',
  'Just',
  'thought',
  'story',
  'dead',
  'avicher',
  'kills',
  'short',
  'thesis'],
 ['Wow',
  ',',
  'good',
  'BKS',
  'T',
  'user',
  '...',
  'sales',
  'Nook',
  '13',
  '%',
  'holidays'],
 ['AC',
  'watch',
  'list',
  '-',
  'volume',
  'pick',
  '139',
  '%',
  'full',
  'day',
  'average',
  '-from',
  '200-day',
  'bounce'],
 ['The',
  'new',
  'wightwatchers',
  'ads',
  'fun',
  'light',
  'regular',
  'people',
  'interesting',
  ',',
  'I',
  'still',
  'dont',
  'trust',
  'WTW',
  '(',
  'position',
  ')'],
 ['AMZN',
  'holding',
  'well',
  '-',
  'next',
  'buy',
  'point',
  'clears',
  'upper',
  'trend',
  'line',
  'heavy',
  'volume'],
 ['MA',
  'exactly',
  'want',
  'see',
  'follow',
  'thru',
  'day',
  'breaking',
  'new',
  'highs',
  'volume'],
 ['ZCS', 'user', 'There', "'s", 'buying'],
 ['AAP', 'SPY', 'QE', '2013', '.', 'Now', 'bring', 'Geithner', '.'],
 ['Over',
  'extended',
  'stock',
  'market',
  '+',
  'unexpected',
  'news',
  'FED',
  'minutes',
  '=',
  'Down',
  'ESD',
  '&',
  'panicky',
  'ES_F',
  'NQ_F',
  '.'],
 ['SPY',
  'ncle',
  'Ben',
  'needed',
  'spice',
  'things',
  'little',
  '.',
  'AAP',
  'people',
  'bored',
  ',',
  'wake',
  '.'],
 ['AAP',
  'might',
  'close',
  'lows',
  'day',
  '.',
  'Bears',
  'control',
  'descending',
  'trendline',
  '.',
  'Watch',
  '.'],
 ['FAN',
  '-',
  'seeking',
  '200d',
  '.',
  'Im',
  'adding',
  'synthetic',
  'shorts',
  'add',
  '200d',
  '.'],
 ['CWST',
  'low',
  'day',
  '4.50',
  ',',
  'near',
  'high',
  'day',
  '4.56',
  ',',
  'watchn',
  'b/out',
  ',',
  'minimal',
  'risk'],
 ['All', ':', 'gme', 'Gamestop', 'short', 'targets', 'spy'],
 ['time', 'get', '#', 'cloud', 'stocks', 'VMW', 'CM'],
 ['BAC',
  'Keep',
  'Overniight',
  'mmy',
  'pos',
  '.',
  'bin',
  'premarket',
  'Tmorrow',
  '.'],
 ['Polk',
  'Expects',
  '2013',
  '.S',
  '.',
  'New',
  'Vehicle',
  'egistrations',
  '15.3',
  'Million',
  '-',
  'Polk',
  '-',
  'F',
  'GM',
  'I',
  'think',
  'low'],
 ['Very',
  'bullish',
  'market',
  'also',
  'talked',
  'trends',
  'SCTY',
  'OST',
  'ANGI',
  'FIO',
  'PANW',
  'A',
  'JCP',
  'P',
  'YEP',
  'MNST',
  'GPN',
  'show',
  '.'],
 ['BAC', 'happens', 'next', '?'],
 ['KCG', 'someone', 'bought', '3.22k', '4', 'Jan', '18', 'Calls', '....'],
 ['Man',
  'I',
  'didnt',
  'know',
  'Skippy',
  'I',
  'made',
  '...',
  'would',
  'thrown',
  'jar',
  'H',
  '#',
  'Hormel'],
 ['Big',
  'move',
  'bonds',
  'today',
  ',',
  '7',
  'months',
  'high',
  '10',
  'rate',
  ',',
  'still',
  'going',
  'lower',
  'ZN_F',
  ',',
  'could',
  'get',
  'truly',
  'ugly',
  'good',
  'NFP',
  'number',
  'AM',
  'SPY',
  'TT'],
 ['Market',
  'Wrap',
  'Video',
  '+',
  'Additions',
  'Watch',
  'ist',
  'including',
  ':',
  'BCEI',
  'BJI',
  'CEE',
  'ES',
  'SONS',
  'SQNM',
  'NX',
  'YEP'],
 ['Maybe',
  'vrng',
  'asked',
  'judge',
  '7',
  '%',
  'royalty',
  'became',
  'risky',
  'goog',
  'deal',
  '?',
  'want',
  'settle'],
 ['BJI', 'Over', '35.53', 'good', 'volume'],
 ['CEE', 'Over', '35.12'],
 ['SQNM', 'Over', '5.05'],
 ['NX', 'On', 'flag', 'break'],
 ['3D',
  'Systems',
  'Brings',
  'Next-Gen',
  'Consumer',
  '3D',
  'Printing',
  'CES',
  '2013',
  'DDD'],
 ['AAP',
  'top',
  'April',
  'Aston',
  'Kutcher',
  'stars',
  "'jOBS",
  "'",
  '.',
  'Kinda',
  'like',
  'Facebook',
  "'Social",
  'Network',
  "'",
  'came',
  '.',
  'FB'],
 ['VNG',
  'w/',
  'MACD',
  'turning',
  '&',
  'signal',
  'line',
  ',',
  'VNG',
  'could',
  'post',
  'nice',
  'rally',
  'current',
  'levels'],
 ['PI',
  '3Q',
  '10Q',
  'operational',
  'cash',
  'flow',
  '9mos',
  '-20million',
  '.',
  '269',
  '%',
  'decline',
  'vs.',
  '9mos',
  'year',
  'ago',
  '.'],
 ['bbby',
  '3Q',
  '10Q',
  'Operational',
  'Cash',
  'Flow',
  '135',
  'million',
  '.',
  '53',
  'increase',
  'vs.',
  'year',
  'ago',
  'Q3',
  '.',
  '64',
  '%',
  'improvement',
  'q',
  'q'],
 ['DI',
  '6mos',
  'operational',
  'cash',
  'flow',
  '267',
  'million',
  '.',
  'increases',
  '187',
  'million',
  'vs.6mos',
  'year',
  'ago',
  '.',
  '233',
  '%',
  'increase'],
 ['AM',
  '3Q',
  '10Q',
  '9mos',
  'operational',
  'cash',
  'flow',
  '32',
  'million',
  'vs.',
  'neg',
  '26',
  'mil',
  '9mos',
  'year',
  'ago',
  '.'],
 ['3Q',
  'operational',
  'cash',
  'flow',
  'neg',
  '16',
  'million',
  '.',
  'vs.',
  'year',
  'ago',
  '3Q',
  'negative',
  '68million',
  '.',
  '52',
  'million',
  'improvement'],
 ['A',
  'quiet',
  'Carl',
  'Icahn',
  '=',
  'Bullish',
  '.',
  'NFX',
  'shorts',
  'paranoid',
  'every',
  'close',
  'get',
  'acquired',
  '.',
  'Think',
  'aapl',
  ',',
  'msft',
  ',',
  'amzn',
  ',',
  'fb'],
 ['I', 'aapl', 'bull', 'break', 'trend', 'line', 'OBV'],
 ['user',
  'Phantom7',
  'I',
  "'ve",
  'calling',
  '+4',
  'ever',
  'since',
  'start',
  'thing',
  '.',
  '3.75',
  'given~',
  'KCG'],
 ['NX',
  'watch',
  'list',
  'small',
  'flag',
  'volume',
  '26',
  '%',
  'ave',
  'full',
  'day',
  'good',
  'volume'],
 ['GOOG',
  'poised',
  'clear',
  'next',
  'resistance',
  '(',
  'buy',
  '/',
  'add',
  'area',
  ')',
  'watch',
  'action',
  '/',
  'volume',
  'closely'],
 ['GDP',
  'watch',
  'list',
  'slightly',
  'line',
  '50-day',
  'EMA',
  'light',
  'volume',
  '5',
  '%',
  'ave',
  'full',
  'day'],
 ['Took', 'profits', 'DDD', ',', 'add', 'breaks', '60', 'volume', '.'],
 ['CHK',
  '-',
  'I',
  "'m",
  'looking',
  '-',
  'small',
  'risk',
  'position',
  'calls',
  '.',
  'Scalp',
  '-',
  'maybe',
  'swing',
  'XE',
  'watch',
  '.'],
 ['ONTY',
  'If',
  'holders',
  'would',
  'hold',
  'raise',
  'ask',
  ',',
  'could',
  'really',
  'pop',
  '.',
  'Going',
  'climb',
  'slowly',
  'regardless',
  '...'],
 ['EOG', 'PXD', 'OAS', '#', 'energyswag'],
 ['AAP',
  'moving',
  'volume',
  '.',
  'Couldnt',
  'cope',
  'descending',
  'trend',
  'line',
  '.',
  'Trend',
  'still',
  '.',
  'Perhaps',
  '460',
  'impossible',
  '.'],
 ['AAP',
  '50EMA',
  'continue',
  'work',
  'AAP',
  'making',
  'lower',
  'highs',
  'MACO',
  'sense'],
 ['Went',
  'short',
  'SPY',
  'yesterday',
  ',',
  'picked',
  'AAP',
  'instead',
  '.',
  'Still',
  'think',
  'market',
  'needs',
  'move',
  'bit',
  'resume',
  'move',
  'upside',
  '.'],
 ['AAP',
  'people',
  'realistic',
  '.',
  'Market',
  'undecided',
  'apple',
  '.',
  'Earnings',
  'lift',
  'cloud',
  '.',
  'If',
  'GOOD',
  'might',
  'EAY',
  'see',
  'reversal',
  '.'],
 ['Will',
  'watch',
  'close',
  'carefully',
  'decide',
  'whether',
  'ONG',
  'SHOT',
  'AAP',
  '.',
  'Below',
  '530',
  'SHOT',
  '!',
  '!',
  '!'],
 ['JCP',
  'Keep',
  'eye',
  'triangle',
  '.',
  'big',
  'short',
  'int',
  ',',
  '34',
  '%',
  '.',
  'reports',
  'Feb',
  '27.',
  'cup',
  '&',
  'handle',
  '.',
  'DT',

In [91]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()

In [92]:
stemedata =[]
for message in stop_token:
  st = [ps.stem(word) for word in message]
  stemedata.append(st)

In [93]:
stemedata

[['kicker',
  'watchlist',
  'xide',
  'tit',
  'soq',
  'pnk',
  'cpw',
  'bpz',
  'aj',
  'trade',
  'method',
  '1',
  'method',
  '2',
  ',',
  'see',
  'prev',
  'post'],
 ['user',
  ':',
  'aap',
  'movi',
  '.',
  '55',
  '%',
  'return',
  'fea/ge',
  'indic',
  '15',
  'trade',
  'year',
  '.',
  'awesom',
  '.'],
 ['user',
  'i',
  "'d",
  'afraid',
  'short',
  'amzn',
  '-',
  'look',
  'like',
  'near-monopoli',
  'ebook',
  'infrastructure-as-a-servic'],
 ['mnta', 'over', '12.00'],
 ['oi', 'over', '21.37'],
 ['pgnx', 'over', '3.04'],
 ['aap',
  '-',
  'user',
  'current',
  'downtrend',
  'break',
  '.',
  'otherwis',
  'short-term',
  'correct',
  'med-term',
  'downtrend',
  '.'],
 ['monday',
  "'s",
  'rel',
  'weak',
  '.',
  'nyx',
  'win',
  'tie',
  'tap',
  'ice',
  'int',
  'bmc',
  'aon',
  'c',
  'chk',
  'biib'],
 ['goog',
  '-',
  'ower',
  'trend',
  'line',
  'channel',
  'test',
  '&',
  'volum',
  'support',
  '.'],
 ['aap', 'watch', 'tomorrow', 'ong', 'entri', '.'],
 ["'m",
  'assum',
  'fcx',
  'open',
  'tomorrow',
  '34.25',
  'trigger',
  'buy',
  '.',
  'still',
  'much',
  'like',
  'setup',
  '.'],
 ['it',
  'realli',
  'worri',
  'everyon',
  'expect',
  'market',
  'ralli',
  ',',
  'usual',
  'exact',
  'opposit',
  'happen',
  'everi',
  'time',
  'shall',
  'see',
  'soon',
  'bac',
  'spx',
  'jpm'],
 ['aap',
  'gamco',
  "'s",
  'arri',
  'haverti',
  ':',
  'appl',
  'is',
  'extrem',
  'cheap',
  'great',
  'video',
  '!',
  '!',
  '!'],
 ['user',
  'maykiljil',
  'post',
  '.',
  'i',
  'agre',
  'msft',
  'go',
  'higher',
  '&',
  'possibl',
  'north',
  '30'],
 ['momentum',
  'come',
  'back',
  'etfc',
  'broke',
  'ma200',
  'resist',
  'solid',
  'volum',
  'friday',
  '.',
  'ong',
  'set-up'],
 ['ha', 'hit', '35.65', 'mean', 'resum', 'target', '42', 'level', '..'],
 ['user',
  'gameplan',
  'shot',
  'today',
  'i',
  'like',
  'trend',
  'break',
  'may',
  'c+h',
  'break',
  '.',
  'oc',
  'weekli',
  'trend',
  'break',
  'back',
  'juli',
  '2011'],
 ['fcx',
  'gap',
  'well',
  'ideal',
  'entri',
  'look',
  'pull',
  'least',
  '35',
  'open',
  'entri'],
 ['user',
  'great',
  'list',
  ',',
  'particularli',
  'like',
  'fisv',
  'syk',
  '.',
  'all',
  'buy',
  '&',
  'hold',
  'type',
  'check',
  'free',
  'list',
  '.'],
 ['athx', 'upper', 'trend', 'line'],
 ['ng',
  '-',
  'nice',
  'pnf',
  'by',
  '-',
  'breakout',
  '-',
  'need',
  'follow',
  'thru'],
 ['wo',
  "n't",
  'believ',
  'aap',
  'uptrend',
  'back',
  'cross',
  'ma',
  '(',
  '50',
  ')'],
 ['x', 'swing', 'still'],
 ['swi', '-', '30', '%', 'float', 'short', 'break', '-', 'ouch'],
 ['biof', 'want', '4.90', "'s", 'comin', '!', '!', '!'],
 ['vs',
  'invert',
  'head',
  'shoulder',
  'play',
  'well',
  '.',
  'wa',
  "n't",
  'abl',
  'catch',
  'entri',
  '.',
  'eye'],
 ['red', ',', 'readi', 'break', '.'],
 ['ei', 'close', 'break', '.', 'my', 'trigger', '30.40', '.'],
 ['user',
  'bac',
  'for',
  'quick',
  'trade',
  'late',
  '..',
  'but',
  'invest',
  '~11.98',
  'good',
  'entri',
  'point',
  'imho'],
 ['chdn',
  '-',
  'ong',
  '49.02',
  '.',
  'trail',
  'stop',
  '56.66',
  '6',
  'prior',
  'stop',
  '54.17',
  ',',
  '49.88',
  ',',
  '49.82',
  ',',
  '45.47',
  ',',
  '43.02',
  '&',
  '41.92',
  '-'],
 ['aap',
  'vome',
  'today',
  'impress',
  '.',
  'at',
  'rate',
  'well',
  'probabl',
  'get',
  '30m',
  'share',
  'trade',
  'today',
  '.'],
 ['user',
  ':',
  'ad',
  'vxi',
  'long',
  'bottom',
  'today',
  'trade',
  ',',
  'also',
  'got',
  'wpi',
  'near',
  'low'],
 ['i',
  'repeat',
  ',',
  'global',
  'economi',
  'go',
  'get',
  'better',
  'year',
  'go',
  'c',
  'instead',
  'bac'],
 ['goog', 'go', 'ong', 'close', '725', '.'],
 ['nkd',
  'look',
  'like',
  'good',
  'short',
  '.',
  'fail',
  'break',
  'price',
  'level',
  'resist',
  '116',
  'today',
  '.'],
 ['gs',
  'like',
  'price',
  'action',
  '.',
  'so',
  'far',
  'hold',
  '130',
  '.',
  'still',
  'decid',
  'whether',
  'go',
  'ong',
  'call',
  'stock',
  '.'],
 ['sbx', 'buy', 'clear', 'resist', '54.5'],
 ['new',
  'target',
  'aap',
  'notic',
  'shakeout',
  'read',
  '-8.49',
  '!',
  'buy',
  'dot',
  'monday'],
 ['too',
  'earli',
  'short',
  'move',
  '.',
  'stock',
  'market',
  'need',
  'day',
  'settl',
  '.',
  '#',
  'patienc',
  'coh',
  'bwd',
  'dt',
  'aap',
  'pay'],
 ['aap',
  'obber',
  'hit',
  'appl',
  'store',
  'pari',
  '.',
  'prefer',
  'take',
  'merchendis',
  'cash',
  '.',
  'bullish',
  '.'],
 ['axa',
  'here',
  'tip',
  'day',
  '.',
  'buy',
  '!',
  'you',
  'even',
  'sign',
  'newslett',
  'anyth',
  'o',
  'if',
  'i',
  "'m",
  'wrong',
  'i',
  'eat',
  'crow',
  ':',
  ')'],
 ['x',
  '1/2',
  'due',
  'move',
  'today',
  'kirbi',
  'daili',
  'around',
  '26.00',
  '-',
  'still',
  'swing',
  '1/2'],
 ['aap',
  '10',
  'min',
  'short',
  'long',
  'fulli',
  'ad',
  ',',
  'look',
  'pop',
  'market',
  ',',
  'shakeout',
  'reset'],
 ['ng',
  'stellar',
  'move',
  '-',
  'still',
  'long',
  'swing',
  '-',
  'full',
  'posit',
  '-',
  'i',
  'believ',
  'user',
  '&',
  'user',
  '2'],
 ['atic', '&', 'tade', 'setp', ':', 'ko', 'an', 'cnx'],
 ['idcc',
  '50sma',
  'act',
  'good',
  'support',
  '.',
  'short-term',
  'momentum',
  'indic',
  'switch',
  'upsid',
  '.'],
 ['new',
  'post',
  ':',
  'bac',
  'is',
  'at',
  '19',
  'month',
  'high',
  ',',
  'but',
  'show',
  'sign',
  'stress'],
 ['c', 'two', 'daili', 'bull', 'flag', 'top', 'other=bullish', 'still'],
 ['ng',
  '-',
  'tradit',
  'at',
  'point',
  'figur',
  '-',
  'bullish',
  'by',
  'signal',
  'multiyear',
  'high'],
 ['jpm',
  'close',
  '>',
  '10sma',
  'monday',
  '(',
  'u',
  'know',
  'rule',
  ')',
  '...',
  'larg',
  'cup',
  'n',
  'handl',
  '....',
  'still',
  'bullish'],
 ['eog',
  'ascend',
  'triangl',
  '-',
  'origin',
  'target',
  '127',
  'extens',
  'ep',
  'feb',
  '11th',
  '?',
  '1/2',
  'posit',
  'swing'],
 ['aapl',
  'daili',
  ',',
  'broke',
  'downtrend',
  '(',
  'close',
  'price',
  ')',
  'w',
  'v',
  'pattern',
  'back',
  'play',
  '.......',
  '600',
  'target'],
 ['phm',
  'pultegroup',
  'option',
  'bear',
  'bet',
  '1.5',
  'million',
  '11',
  '%',
  'move',
  'april'],
 ['bac', 'in', '11.97', 'trade'],
 ['short',
  'setup',
  'display',
  'rel',
  'weak',
  ':',
  'ao',
  'coh',
  'pay',
  'bwd',
  'dt',
  'shd',
  'wtw',
  'p',
  'prepar',
  'short',
  'stall',
  '.',
  'es_f'],
 ['when',
  'amzn',
  'monet',
  'electron',
  'make',
  'traffic',
  'marketplac',
  ',',
  'aap',
  'goog',
  'wake',
  'say',
  "n't",
  'buy',
  'ebay'],
 ['cvi',
  'start',
  'clean',
  'book',
  ',',
  'make',
  'first',
  'buy',
  'yr',
  '-',
  'entri',
  '49.54',
  'stop',
  '47.43'],
 ['sam',
  'cheer',
  'temporari',
  'solut',
  'econom',
  'woe',
  '-',
  'entri',
  '139.81',
  'stop',
  '131.92'],
 ['sk', 'gave', '!'],
 ['ovti',
  'ttm',
  'end',
  'oct',
  '2012',
  'neg',
  '151',
  'million',
  'oper',
  'cash',
  'flow',
  '..',
  '273',
  '%',
  'declin',
  'vs',
  'yoy',
  'ttm',
  'end',
  'oct',
  '2011'],
 ['aap', 'goog', 'respond', 'posit', 'good', 'jobless', 'claim', 'number'],
 ['analyst',
  'price',
  'target',
  'earn',
  'target',
  'come',
  '--',
  '-exacti',
  'want',
  'see',
  'prior',
  'aap',
  'report',
  '.'],
 ['user', 'nice', '!', 'color', 'intc', 'bull', 'well', '!'],
 ['head',
  'p',
  ':',
  'aa',
  'earn',
  '(',
  '1/8/13',
  ')',
  'ess',
  'than',
  'week',
  'away',
  ',',
  'tho',
  'the',
  'season',
  'doe',
  "n't",
  'eay',
  'begin',
  'crank',
  "'til",
  '1/16',
  'w/',
  'gs',
  'jpm',
  'ebay',
  'et',
  'al',
  '...'],
 ['trade',
  'idea',
  'buy',
  'wo',
  'market',
  '26.64',
  ',',
  'target',
  '36',
  ',',
  'cut',
  '23.50'],
 ['trade',
  'idea',
  'buy',
  'dc',
  'market',
  '58.50',
  ',',
  'target',
  '67',
  ',',
  'cut',
  '53'],
 ['goog',
  'look',
  'set',
  'make',
  'new',
  'ath',
  '.',
  'now',
  'e',
  'unknown',
  '.'],
 ['goog', 'trade', 'one', 'long', 'vers', '10sma'],
 ['fnf',
  '-',
  'ong',
  '19.43',
  '.',
  'trail',
  'stop',
  '21.04',
  '6',
  'prior',
  'stop',
  '19.71',
  ',',
  '19.52',
  ',',
  '18.70',
  ',',
  '18.65',
  ',',
  '18.07',
  '17.87',
  '-'],
 ['fod',
  'see',
  'solid',
  'move',
  'tom',
  ',',
  'system',
  'predict',
  'nice',
  'green',
  'candl',
  '.'],
 ['thi',
  'year',
  'fit',
  'health',
  'app',
  '...',
  'winner',
  'gynorm',
  'specul',
  'run',
  'high',
  'nke'],
 ['it', "'s", 'time', 'invest', 'msft', 'compq'],
 ['new',
  'post',
  ':',
  'short',
  'will',
  'make',
  'dime',
  ',',
  'ong',
  'will',
  'make',
  'dollar',
  'aap',
  'spx',
  'qqq',
  'p'],
 ['nbeliev',
  'payment',
  'trend',
  'vc',
  "'s",
  'chase',
  'easili',
  'play',
  'public',
  'market',
  '....',
  'ebay',
  'v',
  'mastercard',
  'ma',
  'time',
  'high'],
 ['some',
  'watch',
  'list',
  'stock',
  'trigger',
  'today',
  'oex',
  'agnx',
  'tv',
  'vbd',
  'xide',
  'ppc',
  'exp',
  'onti',
  'bmn',
  'fs',
  'wk',
  'chmt',
  'fbc',
  'isi',
  'aig'],
 ['nice', 'bull', 'flag', 'breakout', 'oc', '#', 'technolog', '#', 'softwar'],
 ['my',
  'setup',
  'alert',
  'went',
  'bonker',
  'today',
  '..',
  'one',
  'mani',
  'got',
  'triggered.cup+handl',
  'breakout',
  'pfe'],
 ['the',
  'host',
  '....',
  'congrat',
  'cloud',
  'today',
  'ax',
  'user',
  'all-tim',
  'high',
  '.',
  'wow'],
 ['x', 'did', '.s', '.', 'steel', 'just', 'breakout', '?', 'mt'],
 ['dndn',
  'broken',
  'clear',
  '5.5',
  'resistanc',
  'level',
  'heavi',
  'volum',
  '&',
  'could',
  'head',
  'much',
  'higher'],
 ['exp', 'look', 'good', 'higher', 'price'],
 ['apc', 'weekli', 'set', 'long', '.'],
 ['i',
  'go',
  'morn',
  'long',
  '3',
  'aap',
  '560',
  'call',
  'option',
  '&',
  'goog',
  '725',
  'call',
  'jan',
  '4th',
  'expir'],
 ['es_f',
  'path',
  'higher',
  'unthreaten',
  'unless',
  '1452.25',
  'support',
  'fail',
  '.',
  'see',
  'resist',
  '1466.00',
  'spx',
  '#',
  'stock',
  '.'],
 ['monitor',
  's',
  'line/pric',
  'dynam',
  '.',
  'stock',
  'close',
  'dec.28',
  's',
  'line',
  'new',
  'high',
  'be4',
  'price',
  '.',
  'mho',
  'tsm',
  'ipgp',
  'eqix',
  'bc',
  'bdc',
  'ash'],
 ['ddd', 'idcc', 'continu', 'higher'],
 ['had',
  'hope',
  'pick',
  'ost',
  'today',
  ',',
  'look',
  'like',
  'i',
  "'m",
  'day',
  'late',
  '.',
  'nice',
  'move',
  'morn',
  '.'],
 ['gp', 'wow', 'wa', 'fast', 'fast', 'fade', '...'],
 ['amzn',
  'go',
  '260',
  '.',
  'should',
  'go',
  'near',
  '300',
  'market',
  'behav',
  'week',
  '.'],
 ['huston', 'geen', 'aap'],
 ['p', 'long', '9.55'],
 ['hn',
  'breakout',
  '...',
  '3rd',
  'day',
  'look',
  'pullback',
  'enter',
  'long',
  '.'],
 ['ng',
  '-',
  'ascend',
  'triangl',
  'much',
  'like',
  'fs',
  '&',
  'x',
  'breakout',
  '127',
  'exten',
  '161.8',
  'target',
  '-',
  'fib',
  'subject'],
 ['kcg', '...', 'thing', 'make', 'go', 'hmmmm', '?'],
 ['vng', '-', 'huge', 'news', 'patent', 'attorney', 'dan', 'avich'],
 ['ng',
  'nhod',
  '-',
  'check',
  'weekli',
  '-',
  'target',
  'previou',
  'low',
  '2006',
  ':',
  ')'],
 ['ng',
  'nhod',
  '-',
  'see',
  '?',
  'check',
  'weekli',
  '-',
  'target',
  'previou',
  'low',
  '2006',
  ':',
  ')'],
 ['aig',
  'american',
  'intern',
  'group',
  'option',
  'trader',
  'bet',
  '4',
  '%',
  'move',
  'next',
  'friday'],
 ['p', 'balanc', '+.32'],
 ['vng', 'buy', 'vs.', 'sell', '?'],
 ['bac',
  'in',
  '12.00',
  'sinc',
  'consolid',
  'level',
  '.',
  'we',
  'could',
  'close',
  '=',
  '>',
  '12.09',
  'market',
  'stabl',
  'pm',
  'imho',
  '.'],
 ['vng', 'parabol', 'move', 'comin', "'"],
 ['new',
  'soni',
  'pre-own',
  'block',
  'tech',
  'patent',
  'unearth',
  'sne',
  '...',
  '50',
  '%',
  'gme',
  'profit',
  'pre',
  'own',
  '..',
  'last',
  'one',
  'turn',
  'light'],
 ['like',
  'vs',
  ',',
  'love',
  'wynn',
  '111',
  'entri',
  'new',
  'target',
  'yesterday',
  '121.',
  'nice',
  '!'],
 ['user',
  ':',
  'spx',
  '1464.90',
  'wave',
  'iv',
  'would',
  '20',
  'point',
  'lower',
  '[',
  '1467.00',
  'key',
  ']',
  'es_f',
  'hod',
  '1460.00',
  '(',
  'necklin',
  '1458.50',
  'bearish',
  ')'],
 ['ddd',
  'consolid',
  'strong',
  'move',
  'previou',
  'day',
  '55',
  '60',
  ',',
  'next',
  'buy',
  'point',
  '60',
  'volum',
  '(',
  'hold',
  ')',
  '.'],
 ['vng',
  '-',
  '12',
  'mil',
  'share',
  'short',
  'plu',
  'long',
  'buy',
  '=',
  'massiv',
  'vng',
  'short',
  'squeez',
  '.',
  'just',
  'thought',
  'stori',
  'dead',
  'avich',
  'kill',
  'short',
  'thesi'],
 ['wow',
  ',',
  'good',
  'bk',
  't',
  'user',
  '...',
  'sale',
  'nook',
  '13',
  '%',
  'holiday'],
 ['ac',
  'watch',
  'list',
  '-',
  'volum',
  'pick',
  '139',
  '%',
  'full',
  'day',
  'averag',
  '-from',
  '200-day',
  'bounc'],
 ['the',
  'new',
  'wightwatch',
  'ad',
  'fun',
  'light',
  'regular',
  'peopl',
  'interest',
  ',',
  'i',
  'still',
  'dont',
  'trust',
  'wtw',
  '(',
  'posit',
  ')'],
 ['amzn',
  'hold',
  'well',
  '-',
  'next',
  'buy',
  'point',
  'clear',
  'upper',
  'trend',
  'line',
  'heavi',
  'volum'],
 ['ma',
  'exactli',
  'want',
  'see',
  'follow',
  'thru',
  'day',
  'break',
  'new',
  'high',
  'volum'],
 ['zc', 'user', 'there', "'s", 'buy'],
 ['aap', 'spi', 'qe', '2013', '.', 'now', 'bring', 'geithner', '.'],
 ['over',
  'extend',
  'stock',
  'market',
  '+',
  'unexpect',
  'news',
  'fed',
  'minut',
  '=',
  'down',
  'esd',
  '&',
  'panicki',
  'es_f',
  'nq_f',
  '.'],
 ['spi',
  'ncle',
  'ben',
  'need',
  'spice',
  'thing',
  'littl',
  '.',
  'aap',
  'peopl',
  'bore',
  ',',
  'wake',
  '.'],
 ['aap',
  'might',
  'close',
  'low',
  'day',
  '.',
  'bear',
  'control',
  'descend',
  'trendlin',
  '.',
  'watch',
  '.'],
 ['fan',
  '-',
  'seek',
  '200d',
  '.',
  'im',
  'ad',
  'synthet',
  'short',
  'add',
  '200d',
  '.'],
 ['cwst',
  'low',
  'day',
  '4.50',
  ',',
  'near',
  'high',
  'day',
  '4.56',
  ',',
  'watchn',
  'b/out',
  ',',
  'minim',
  'risk'],
 ['all', ':', 'gme', 'gamestop', 'short', 'target', 'spi'],
 ['time', 'get', '#', 'cloud', 'stock', 'vmw', 'cm'],
 ['bac',
  'keep',
  'overniight',
  'mmi',
  'po',
  '.',
  'bin',
  'premarket',
  'tmorrow',
  '.'],
 ['polk',
  'expect',
  '2013',
  '.s',
  '.',
  'new',
  'vehicl',
  'egistr',
  '15.3',
  'million',
  '-',
  'polk',
  '-',
  'f',
  'gm',
  'i',
  'think',
  'low'],
 ['veri',
  'bullish',
  'market',
  'also',
  'talk',
  'trend',
  'scti',
  'ost',
  'angi',
  'fio',
  'panw',
  'a',
  'jcp',
  'p',
  'yep',
  'mnst',
  'gpn',
  'show',
  '.'],
 ['bac', 'happen', 'next', '?'],
 ['kcg', 'someon', 'bought', '3.22k', '4', 'jan', '18', 'call', '....'],
 ['man',
  'i',
  'didnt',
  'know',
  'skippi',
  'i',
  'made',
  '...',
  'would',
  'thrown',
  'jar',
  'h',
  '#',
  'hormel'],
 ['big',
  'move',
  'bond',
  'today',
  ',',
  '7',
  'month',
  'high',
  '10',
  'rate',
  ',',
  'still',
  'go',
  'lower',
  'zn_f',
  ',',
  'could',
  'get',
  'truli',
  'ugli',
  'good',
  'nfp',
  'number',
  'am',
  'spi',
  'tt'],
 ['market',
  'wrap',
  'video',
  '+',
  'addit',
  'watch',
  'ist',
  'includ',
  ':',
  'bcei',
  'bji',
  'cee',
  'es',
  'son',
  'sqnm',
  'nx',
  'yep'],
 ['mayb',
  'vrng',
  'ask',
  'judg',
  '7',
  '%',
  'royalti',
  'becam',
  'riski',
  'goog',
  'deal',
  '?',
  'want',
  'settl'],
 ['bji', 'over', '35.53', 'good', 'volum'],
 ['cee', 'over', '35.12'],
 ['sqnm', 'over', '5.05'],
 ['nx', 'on', 'flag', 'break'],
 ['3d',
  'system',
  'bring',
  'next-gen',
  'consum',
  '3d',
  'print',
  'ce',
  '2013',
  'ddd'],
 ['aap',
  'top',
  'april',
  'aston',
  'kutcher',
  'star',
  "'job",
  "'",
  '.',
  'kinda',
  'like',
  'facebook',
  "'social",
  'network',
  "'",
  'came',
  '.',
  'fb'],
 ['vng',
  'w/',
  'macd',
  'turn',
  '&',
  'signal',
  'line',
  ',',
  'vng',
  'could',
  'post',
  'nice',
  'ralli',
  'current',
  'level'],
 ['pi',
  '3q',
  '10q',
  'oper',
  'cash',
  'flow',
  '9mo',
  '-20million',
  '.',
  '269',
  '%',
  'declin',
  'vs.',
  '9mo',
  'year',
  'ago',
  '.'],
 ['bbbi',
  '3q',
  '10q',
  'oper',
  'cash',
  'flow',
  '135',
  'million',
  '.',
  '53',
  'increas',
  'vs.',
  'year',
  'ago',
  'q3',
  '.',
  '64',
  '%',
  'improv',
  'q',
  'q'],
 ['di',
  '6mo',
  'oper',
  'cash',
  'flow',
  '267',
  'million',
  '.',
  'increas',
  '187',
  'million',
  'vs.6mo',
  'year',
  'ago',
  '.',
  '233',
  '%',
  'increas'],
 ['am',
  '3q',
  '10q',
  '9mo',
  'oper',
  'cash',
  'flow',
  '32',
  'million',
  'vs.',
  'neg',
  '26',
  'mil',
  '9mo',
  'year',
  'ago',
  '.'],
 ['3q',
  'oper',
  'cash',
  'flow',
  'neg',
  '16',
  'million',
  '.',
  'vs.',
  'year',
  'ago',
  '3q',
  'neg',
  '68million',
  '.',
  '52',
  'million',
  'improv'],
 ['a',
  'quiet',
  'carl',
  'icahn',
  '=',
  'bullish',
  '.',
  'nfx',
  'short',
  'paranoid',
  'everi',
  'close',
  'get',
  'acquir',
  '.',
  'think',
  'aapl',
  ',',
  'msft',
  ',',
  'amzn',
  ',',
  'fb'],
 ['i', 'aapl', 'bull', 'break', 'trend', 'line', 'obv'],
 ['user',
  'phantom7',
  'i',
  "'ve",
  'call',
  '+4',
  'ever',
  'sinc',
  'start',
  'thing',
  '.',
  '3.75',
  'given~',
  'kcg'],
 ['nx',
  'watch',
  'list',
  'small',
  'flag',
  'volum',
  '26',
  '%',
  'ave',
  'full',
  'day',
  'good',
  'volum'],
 ['goog',
  'pois',
  'clear',
  'next',
  'resist',
  '(',
  'buy',
  '/',
  'add',
  'area',
  ')',
  'watch',
  'action',
  '/',
  'volum',
  'close'],
 ['gdp',
  'watch',
  'list',
  'slightli',
  'line',
  '50-day',
  'ema',
  'light',
  'volum',
  '5',
  '%',
  'ave',
  'full',
  'day'],
 ['took', 'profit', 'ddd', ',', 'add', 'break', '60', 'volum', '.'],
 ['chk',
  '-',
  'i',
  "'m",
  'look',
  '-',
  'small',
  'risk',
  'posit',
  'call',
  '.',
  'scalp',
  '-',
  'mayb',
  'swing',
  'xe',
  'watch',
  '.'],
 ['onti',
  'if',
  'holder',
  'would',
  'hold',
  'rais',
  'ask',
  ',',
  'could',
  'realli',
  'pop',
  '.',
  'go',
  'climb',
  'slowli',
  'regardless',
  '...'],
 ['eog', 'pxd', 'oa', '#', 'energyswag'],
 ['aap',
  'move',
  'volum',
  '.',
  'couldnt',
  'cope',
  'descend',
  'trend',
  'line',
  '.',
  'trend',
  'still',
  '.',
  'perhap',
  '460',
  'imposs',
  '.'],
 ['aap',
  '50ema',
  'continu',
  'work',
  'aap',
  'make',
  'lower',
  'high',
  'maco',
  'sens'],
 ['went',
  'short',
  'spi',
  'yesterday',
  ',',
  'pick',
  'aap',
  'instead',
  '.',
  'still',
  'think',
  'market',
  'need',
  'move',
  'bit',
  'resum',
  'move',
  'upsid',
  '.'],
 ['aap',
  'peopl',
  'realist',
  '.',
  'market',
  'undecid',
  'appl',
  '.',
  'earn',
  'lift',
  'cloud',
  '.',
  'if',
  'good',
  'might',
  'eay',
  'see',
  'revers',
  '.'],
 ['will',
  'watch',
  'close',
  'care',
  'decid',
  'whether',
  'ong',
  'shot',
  'aap',
  '.',
  'below',
  '530',
  'shot',
  '!',
  '!',
  '!'],
 ['jcp',
  'keep',
  'eye',
  'triangl',
  '.',
  'big',
  'short',
  'int',
  ',',
  '34',
  '%',
  '.',
  'report',
  'feb',
  '27.',
  'cup',
  '&',
  'handl',
  '.',
  'dt',
  '.',
  'ong'],
 ['sold', 'littl', 'goog', '...', 'first', 'time'],
 ['nice', 'cup', 'handl', 'breakout', 'mca'],
 ['faf', 'new', 'high', '.'],
 ['spi', 'give', 'aap', 'finger', '.', 'we', "n't", 'care', 'anymor', 'lol'],
 ['the', 'smith', '&', 'corona', 'ok.', 'amzn'],
 ['va',
  '-',
  'ong',
  '43.07',
  '.',
  'trail',
  'stop',
  '58.98',
  '11',
  'stop',
  '54.53',
  ',',
  '52.45',
  ',',
  '48.05',
  ',',
  '47.32',
  ',',
  '46.71',
  ',',
  '...',
  '41.32',
  '&',
  '39.57',
  '-'],
 ['amzn',
  'alert',
  'updat',
  ':',
  'last',
  'minut',
  'push',
  'tri',
  'shake',
  'put',
  '.',
  "'re",
  'hang',
  '.'],
 ['aap', 'volum', 'higher', 'today', 'monday', '.', 'keep', 'mind', '.'],
 ['hb.a',
  '-',
  'ong',
  '73.67',
  '.',

In [94]:
#apply pos_tagging on data
from nltk.tag import pos_tag
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\mehna\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

In [95]:
pos_token=[pos_tag(message) for message in stop_token]

In [96]:
pos_token

[[('Kickers', 'NNS'),
  ('watchlist', 'VBP'),
  ('XIDE', 'NNP'),
  ('TIT', 'NNP'),
  ('SOQ', 'NNP'),
  ('PNK', 'NNP'),
  ('CPW', 'NNP'),
  ('BPZ', 'NNP'),
  ('AJ', 'NNP'),
  ('trade', 'NN'),
  ('method', 'NN'),
  ('1', 'CD'),
  ('method', 'NN'),
  ('2', 'CD'),
  (',', ','),
  ('see', 'VBP'),
  ('prev', 'JJ'),
  ('posts', 'NNS')],
 [('user', 'NN'),
  (':', ':'),
  ('AAP', 'NNP'),
  ('MOVIE', 'NNP'),
  ('.', '.'),
  ('55', 'CD'),
  ('%', 'NN'),
  ('return', 'NN'),
  ('FEA/GEED', 'NNP'),
  ('indicator', 'NN'),
  ('15', 'CD'),
  ('trades', 'NNS'),
  ('year', 'NN'),
  ('.', '.'),
  ('AWESOME', 'NNP'),
  ('.', '.')],
 [('user', 'NN'),
  ('I', 'PRP'),
  ("'d", 'MD'),
  ('afraid', 'VB'),
  ('short', 'JJ'),
  ('AMZN', 'NNP'),
  ('-', ':'),
  ('looking', 'VBG'),
  ('like', 'IN'),
  ('near-monopoly', 'JJ'),
  ('eBooks', 'NNS'),
  ('infrastructure-as-a-service', 'JJ')],
 [('MNTA', 'NNP'), ('Over', 'NNP'), ('12.00', 'CD')],
 [('OI', 'NNP'), ('Over', 'NNP'), ('21.37', 'CD')],
 [('PGNX', 'NNP'), ('Over', 'NNP'), ('3.04', 'CD')],
 [('AAP', 'NNP'),
  ('-', ':'),
  ('user', 'NN'),
  ('current', 'JJ'),
  ('downtrend', 'NN'),
  ('break', 'NN'),
  ('.', '.'),
  ('Otherwise', 'RB'),
  ('short-term', 'JJ'),
  ('correction', 'NN'),
  ('med-term', 'JJ'),
  ('downtrend', 'NN'),
  ('.', '.')],
 [('Monday', 'NNP'),
  ("'s", 'POS'),
  ('relative', 'JJ'),
  ('weakness', 'NN'),
  ('.', '.'),
  ('NYX', 'NNP'),
  ('WIN', 'NNP'),
  ('TIE', 'NNP'),
  ('TAP', 'NNP'),
  ('ICE', 'NNP'),
  ('INT', 'NNP'),
  ('BMC', 'NNP'),
  ('AON', 'NNP'),
  ('C', 'NNP'),
  ('CHK', 'NNP'),
  ('BIIB', 'NNP')],
 [('GOOG', 'NNP'),
  ('-', ':'),
  ('ower', 'JJR'),
  ('trend', 'NN'),
  ('line', 'NN'),
  ('channel', 'NN'),
  ('test', 'NN'),
  ('&', 'CC'),
  ('volume', 'NN'),
  ('support', 'NN'),
  ('.', '.')],
 [('AAP', 'NNP'),
  ('watch', 'NN'),
  ('tomorrow', 'NN'),
  ('ONG', 'NNP'),
  ('entry', 'NN'),
  ('.', '.')],
 [("'m", 'VBP'),
  ('assuming', 'VBG'),
  ('FCX', 'NNP'),
  ('opens', 'VBZ'),
  ('tomorrow', 'NN'),
  ('34.25', 'CD'),
  ('trigger', 'NN'),
  ('buy', 'NN'),
  ('.', '.'),
  ('still', 'RB'),
  ('much', 'JJ'),
  ('like', 'IN'),
  ('setup', 'NN'),
  ('.', '.')],
 [('It', 'PRP'),
  ('really', 'RB'),
  ('worries', 'VBZ'),
  ('everyone', 'NN'),
  ('expects', 'VBZ'),
  ('market', 'NN'),
  ('rally', 'NN'),
  (',', ','),
  ('usually', 'RB'),
  ('exact', 'JJ'),
  ('opposite', 'JJ'),
  ('happens', 'NNS'),
  ('every', 'DT'),
  ('time', 'NN'),
  ('shall', 'MD'),
  ('see', 'VB'),
  ('soon', 'RB'),
  ('bac', 'JJ'),
  ('spx', 'NN'),
  ('jpm', 'NN')],
 [('AAP', 'NNP'),
  ('GAMCO', 'NNP'),
  ("'s", 'POS'),
  ('arry', 'JJ'),
  ('Haverty', 'NNP'),
  (':', ':'),
  ('Apple', 'NNP'),
  ('Is', 'VBZ'),
  ('Extremely', 'RB'),
  ('Cheap', 'JJ'),
  ('Great', 'NNP'),
  ('Video', 'NNP'),
  ('!', '.'),
  ('!', '.'),
  ('!', '.')],
 [('user', 'NN'),
  ('Maykiljil', 'NNP'),
  ('posted', 'VBD'),
  ('.', '.'),
  ('I', 'PRP'),
  ('agree', 'VBP'),
  ('MSFT', 'NNP'),
  ('going', 'VBG'),
  ('higher', 'JJR'),
  ('&', 'CC'),
  ('possibly', 'RB'),
  ('north', 'JJ'),
  ('30', 'CD')],
 [('Momentum', 'NNP'),
  ('coming', 'VBG'),
  ('back', 'RB'),
  ('ETFC', 'NNP'),
  ('Broke', 'NNP'),
  ('MA200', 'NNP'),
  ('resistance', 'NN'),
  ('solid', 'JJ'),
  ('volume', 'NN'),
  ('Friday', 'NNP'),
  ('.', '.'),
  ('ong', 'JJ'),
  ('set-up', 'JJ')],
 [('HA', 'NNP'),
  ('Hitting', 'NNP'),
  ('35.65', 'CD'),
  ('means', 'NNS'),
  ('resume', 'VBP'),
  ('targeting', 'VBG'),
  ('42', 'CD'),
  ('level', 'NN'),
  ('..', 'NN')],
 [('user', 'NN'),
  ('gameplan', 'NN'),
  ('shot', 'NN'),
  ('today', 'NN'),
  ('I', 'PRP'),
  ('liked', 'VBD'),
  ('trend', 'NN'),
  ('break', 'NN'),
  ('May', 'NNP'),
  ('c+h', 'NN'),
  ('break', 'NN'),
  ('.', '.'),
  ('OC', 'NNP'),
  ('weekly', 'JJ'),
  ('trend', 'NN'),
  ('break', 'NN'),
  ('back', 'RB'),
  ('july', 'NN'),
  ('2011', 'CD')],
 [('FCX', 'NNP'),
  ('gapping', 'VBG'),
  ('well', 'RB'),
  ('ideal', 'JJ'),
  ('entry', 'NN'),
  ('looking', 'VBG'),
  ('pull', 'JJ'),
  ('least', 'JJS'),
  ('35', 'CD'),
  ('open', 'JJ'),
  ('entry', 'NN')],
 [('user', 'RB'),
  ('great', 'JJ'),
  ('list', 'NN'),
  (',', ','),
  ('particularly', 'RB'),
  ('like', 'IN'),
  ('FISV', 'NNP'),
  ('SYK', 'NNP'),
  ('.', '.'),
  ('All', 'NNP'),
  ('buy', 'VBP'),
  ('&', 'CC'),
  ('hold', 'VBP'),
  ('types', 'NNS'),
  ('check', 'VB'),
  ('free', 'JJ'),
  ('list', 'NN'),
  ('.', '.')],
 [('ATHX', 'NNP'), ('upper', 'JJ'), ('trend', 'NN'), ('line', 'NN')],
 [('NG', 'NNP'),
  ('-', ':'),
  ('nice', 'JJ'),
  ('PNF', 'NNP'),
  ('BY', 'NNP'),
  ('-', ':'),
  ('breakout', 'NN'),
  ('-', ':'),
  ('need', 'NN'),
  ('follow', 'VBP'),
  ('thru', 'NN')],
 [('Wo', 'VBP'),
  ("n't", 'RB'),
  ('believe', 'VB'),
  ('AAP', 'NNP'),
  ('uptrend', 'VB'),
  ('back', 'RB'),
  ('crosses', 'NNS'),
  ('MA', 'NNP'),
  ('(', '('),
  ('50', 'CD'),
  (')', ')')],
 [('X', 'NN'), ('swing', 'NN'), ('still', 'RB')],
 [('SWY', 'NNP'),
  ('-', ':'),
  ('30', 'CD'),
  ('%', 'NN'),
  ('float', 'NN'),
  ('short', 'JJ'),
  ('breaking', 'VBG'),
  ('-', ':'),
  ('ouch', 'JJ')],
 [('BIOF', 'NNP'),
  ('wants', 'VBZ'),
  ('4.90', 'CD'),
  ("'s", 'POS'),
  ('comin', 'NN'),
  ('!', '.'),
  ('!', '.'),
  ('!', '.')],
 [('VS', 'NNP'),
  ('inverted', 'VBD'),
  ('head', 'NN'),
  ('shoulder', 'NN'),
  ('play', 'NN'),
  ('well', 'RB'),
  ('.', '.'),
  ('Was', 'VBP'),
  ("n't", 'RB'),
  ('able', 'JJ'),
  ('catch', 'VB'),
  ('entry', 'NN'),
  ('.', '.'),
  ('Eyes', 'NNS')],
 [('red', 'JJ'), (',', ','), ('ready', 'JJ'), ('break', 'NN'), ('.', '.')],
 [('EI', 'NNP'),
  ('close', 'RB'),
  ('breaking', 'VBG'),
  ('.', '.'),
  ('My', 'NNP'),
  ('trigger', 'NN'),
  ('30.40', 'CD'),
  ('.', '.')],
 [('user', 'NN'),
  ('BAC', 'NNP'),
  ('For', 'IN'),
  ('quick', 'JJ'),
  ('Trade', 'NNP'),
  ('late', 'JJ'),
  ('..', 'NNS'),
  ('But', 'CC'),
  ('investing', 'VBG'),
  ('~11.98', 'RB'),
  ('good', 'JJ'),
  ('entry', 'NN'),
  ('point', 'NN'),
  ('IMHO', 'NNP')],
 [('CHDN', 'NNP'),
  ('-', ':'),
  ('ong', 'RB'),
  ('49.02', 'CD'),
  ('.', '.'),
  ('Trailing', 'VBG'),
  ('Stop', 'NNP'),
  ('56.66', 'CD'),
  ('6', 'CD'),
  ('prior', 'JJ'),
  ('Stops', 'NNP'),
  ('54.17', 'CD'),
  (',', ','),
  ('49.88', 'CD'),
  (',', ','),
  ('49.82', 'CD'),
  (',', ','),
  ('45.47', 'CD'),
  (',', ','),
  ('43.02', 'CD'),
  ('&', 'CC'),
  ('41.92', 'CD'),
  ('-', ':')],
 [('AAP', 'NNP'),
  ('VOME', 'NNP'),
  ('today', 'NN'),
  ('impressive', 'JJ'),
  ('.', '.'),
  ('At', 'IN'),
  ('rate', 'NN'),
  ('well', 'NN'),
  ('probably', 'RB'),
  ('get', 'VB'),
  ('30M', 'CD'),
  ('shares', 'NNS'),
  ('traded', 'VBN'),
  ('today', 'NN'),
  ('.', '.')],
 [('user', 'NN'),
  (':', ':'),
  ('adding', 'VBG'),
  ('VXY', 'NNP'),
  ('long', 'JJ'),
  ('bottom', 'NN'),
  ('today', 'NN'),
  ('trade', 'NN'),
  (',', ','),
  ('also', 'RB'),
  ('got', 'VBD'),
  ('WPI', 'NNP'),
  ('near', 'IN'),
  ('low', 'JJ')],
 [('I', 'PRP'),
  ('repeat', 'VBP'),
  (',', ','),
  ('global', 'JJ'),
  ('economy', 'NN'),
  ('going', 'VBG'),
  ('get', 'VB'),
  ('better', 'JJR'),
  ('year', 'NN'),
  ('go', 'VBP'),
  ('C', 'NNP'),
  ('instead', 'RB'),
  ('BAC', 'NNP')],
 [('GOOG', 'NNP'),
  ('go', 'VBP'),
  ('ONG', 'NNP'),
  ('close', 'RB'),
  ('725', 'CD'),
  ('.', '.')],
 [('NKD', 'NNP'),
  ('looking', 'VBG'),
  ('like', 'IN'),
  ('good', 'JJ'),
  ('short', 'JJ'),
  ('.', '.'),
  ('Failed', 'VBD'),
  ('break', 'JJ'),
  ('price', 'NN'),
  ('level', 'NN'),
  ('resistance', 'NN'),
  ('116', 'CD'),
  ('today', 'NN'),
  ('.', '.')],
 [('GS', 'NNP'),
  ('like', 'IN'),
  ('price', 'NN'),
  ('action', 'NN'),
  ('.', '.'),
  ('So', 'RB'),
  ('far', 'RB'),
  ('holding', 'VBG'),
  ('130', 'CD'),
  ('.', '.'),
  ('Still', 'RB'),
  ('deciding', 'VBG'),
  ('whether', 'IN'),
  ('go', 'VB'),
  ('ONG', 'NNP'),
  ('calls', 'VBZ'),
  ('stocks', 'NNS'),
  ('.', '.')],
 [('SBX', 'NNP'),
  ('buy', 'VBP'),
  ('clears', 'NNS'),
  ('resistance', 'VBP'),
  ('54.5', 'CD')],
 [('NEW', 'NNP'),
  ('target', 'NN'),
  ('AAP', 'NNP'),
  ('notice', 'NN'),
  ('shakeout', 'NN'),
  ('reading', 'VBG'),
  ('-8.49', 'NN'),
  ('!', '.'),
  ('buy', 'VB'),
  ('dot', 'NNS'),
  ('Monday', 'NNP')],
 [('Too', 'RB'),
  ('early', 'JJ'),
  ('short', 'JJ'),
  ('move', 'NN'),
  ('.', '.'),
  ('Stock', 'NNP'),
  ('Market', 'NNP'),
  ('needs', 'VBZ'),
  ('days', 'NNS'),
  ('settle', 'VB'),
  ('.', '.'),
  ('#', '#'),
  ('Patience', 'NNP'),
  ('COH', 'NNP'),
  ('BWD', 'NNP'),
  ('DT', 'NNP'),
  ('AAP', 'NNP'),
  ('PAY', 'NNP')],
 [('AAP', 'NNP'),
  ('obbers', 'NNS'),
  ('hit', 'VBP'),
  ('Apple', 'NNP'),
  ('Store', 'NNP'),
  ('Paris', 'NNP'),
  ('.', '.'),
  ('Prefer', 'NNP'),
  ('take', 'VBP'),
  ('merchendise', 'NN'),
  ('cash', 'NN'),
  ('.', '.'),
  ('Bullish', 'JJ'),
  ('.', '.')],
 [('AXA', 'NNP'),
  ('Here', 'RB'),
  ('tip', 'RB'),
  ('day', 'NN'),
  ('.', '.'),
  ('Buy', 'VB'),
  ('!', '.'),
  ('You', 'PRP'),
  ('even', 'RB'),
  ('sign', 'VBP'),
  ('newsletter', 'NN'),
  ('anything', 'NN'),
  ('O', 'NNP'),
  ('If', 'IN'),
  ('I', 'PRP'),
  ("'m", 'VBP'),
  ('wrong', 'JJ'),
  ('I', 'PRP'),
  ('eat', 'VBP'),
  ('crow', 'NNS'),
  (':', ':'),
  (')', ')')],
 [('X', '$'),
  ('1/2', 'CD'),
  ('due', 'JJ'),
  ('move', 'NN'),
  ('today', 'NN'),
  ('Kirby', 'NNP'),
  ('daily', 'RB'),
  ('around', 'IN'),
  ('26.00', 'CD'),
  ('-', ':'),
  ('still', 'RB'),
  ('swinging', 'VBG'),
  ('1/2', 'CD')],
 [('AAP', '$'),
  ('10', 'CD'),
  ('min', 'NN'),
  ('short', 'JJ'),
  ('longs', 'NNS'),
  ('fully', 'RB'),
  ('added', 'VBD'),
  (',', ','),
  ('look', 'VB'),
  ('pop', 'JJ'),
  ('market', 'NN'),
  (',', ','),
  ('shakeout', 'NN'),
  ('reset', 'NN')],
 [('NG', 'NNP'),
  ('stellar', 'JJ'),
  ('move', 'NN'),
  ('-', ':'),
  ('still', 'RB'),
  ('long', 'RB'),
  ('swing', 'VBG'),
  ('-', ':'),
  ('full', 'JJ'),
  ('position', 'NN'),
  ('-', ':'),
  ('I', 'PRP'),
  ('believe', 'VBP'),
  ('user', 'JJ'),
  ('&', 'CC'),
  ('user', 'JJ'),
  ('2', 'CD')],
 [('ATICE', 'NNP'),
  ('&', 'CC'),
  ('TADE', 'NNP'),
  ('SETP', 'NNP'),
  (':', ':'),
  ('KO', 'NNP'),
  ('AN', 'NNP'),
  ('CNX', 'NNP')],
 [('IDCC', 'NNP'),
  ('50SMA', 'CD'),
  ('acting', 'VBG'),
  ('good', 'JJ'),
  ('support', 'NN'),
  ('.', '.'),
  ('Short-term', 'JJ'),
  ('momentum', 'NN'),
  ('indicators', 'NNS'),
  ('switched', 'VBD'),
  ('upside', 'RB'),
  ('.', '.')],
 [('NEW', 'JJ'),
  ('POST', 'NNP'),
  (':', ':'),
  ('BAC', 'NN'),
  ('Is', 'VBZ'),
  ('At', 'IN'),
  ('19', 'CD'),
  ('Month', 'NNP'),
  ('Highs', 'NNP'),
  (',', ','),
  ('But', 'CC'),
  ('Showing', 'NNP'),
  ('Signs', 'NNP'),
  ('Stress', 'NNP')],
 [('c', 'NNS'),
  ('two', 'CD'),
  ('daily', 'JJ'),
  ('bull', 'NN'),
  ('flags', 'NNS'),
  ('top', 'JJ'),
  ('other=bullish', 'NN'),
  ('still', 'RB')],
 [('NG', 'NNP'),
  ('-', ':'),
  ('traditional', 'JJ'),
  ('AT', 'NNP'),
  ('point', 'NN'),
  ('figure', 'NN'),
  ('-', ':'),
  ('bullish', 'NN'),
  ('BY', 'NNP'),
  ('signals', 'NNS'),
  ('multiyear', 'VBP'),
  ('high', 'JJ')],
 [('jpm', 'NN'),
  ('closed', 'VBD'),
  ('>', 'RB'),
  ('10sma', 'CD'),
  ('Monday', 'NNP'),
  ('(', '('),
  ('u', 'JJ'),
  ('know', 'VBP'),
  ('rules', 'NNS'),
  (')', ')'),
  ('...', ':'),
  ('large', 'JJ'),
  ('cup', 'NN'),
  ('n', 'NN'),
  ('handle', 'NN'),
  ('....', 'NNP'),
  ('still', 'RB'),
  ('bullish', 'VB')],
 [('EOG', 'NNP'),
  ('ascending', 'VBG'),
  ('triangle', 'SYM'),
  ('-', ':'),
  ('original', 'JJ'),
  ('target', 'NN'),
  ('127', 'CD'),
  ('extension', 'NN'),
  ('EPS', 'NNP'),
  ('Feb', 'NNP'),
  ('11th', 'CD'),
  ('?', '.'),
  ('1/2', 'CD'),
  ('position', 'NN'),
  ('swing', 'NN')],
 [('aapl', 'JJ'),
  ('daily', 'RB'),
  (',', ','),
  ('broke', 'VBD'),
  ('downtrend', 'NN'),
  ('(', '('),
  ('closing', 'VBG'),
  ('prices', 'NNS'),
  (')', ')'),
  ('w', 'VBP'),
  ('v', 'JJ'),
  ('pattern', 'NN'),
  ('back', 'RB'),
  ('play', 'NN'),
  ('.......', 'VBD'),
  ('600', 'CD'),
  ('target', 'NN')],
 [('PHM', 'NNP'),
  ('PulteGroup', 'NNP'),
  ('Option', 'NNP'),
  ('Bear', 'NNP'),
  ('bets', 'VBZ'),
  ('1.5', 'CD'),
  ('Million', 'NNP'),
  ('11', 'CD'),
  ('%', 'NN'),
  ('move', 'NN'),
  ('April', 'NNP')],
 [('BAC', 'NNP'), ('In', 'IN'), ('11.97', 'CD'), ('trade', 'NN')],
 [('Short', 'JJ'),
  ('Setups', 'NNP'),
  ('displaying', 'VBG'),
  ('relative', 'JJ'),
  ('weakness', 'NN'),
  (':', ':'),
  ('AO', 'NNP'),
  ('COH', 'NNP'),
  ('PAY', 'NNP'),
  ('BWD', 'NNP'),
  ('DT', 'NNP'),
  ('SHD', 'NNP'),
  ('WTW', 'NNP'),
  ('P', 'NNP'),
  ('Prepare', 'NNP'),
  ('short', 'JJ'),
  ('stall', 'NN'),
  ('.', '.'),
  ('ES_F', 'NN')],
 [('When', 'WRB'),
  ('AMZN', 'NNP'),
  ('monetize', 'VB'),
  ('electronics', 'NNS'),
  ('makes', 'VBZ'),
  ('traffic', 'NN'),
  ('marketplace', 'NN'),
  (',', ','),
  ('AAP', 'NNP'),
  ('GOOG', 'NNP'),
  ('wake', 'VBP'),
  ('say', 'VBP'),
  ("n't", 'RB'),
  ('buy', 'VB'),
  ('EBAY', 'NNP')],
 [('CVI', 'NNP'),
  ('starting', 'VBG'),
  ('clean', 'JJ'),
  ('book', 'NN'),
  (',', ','),
  ('making', 'VBG'),
  ('first', 'JJ'),
  ('buy', 'VB'),
  ('yr', 'SYM'),
  ('-', ':'),
  ('entry', 'NN'),
  ('49.54', 'CD'),
  ('stop', 'NN'),
  ('47.43', 'CD')],
 [('SAM', 'NNP'),
  ('cheers', 'NNS'),
  ('temporary', 'JJ'),
  ('solution', 'NN'),
  ('economic', 'JJ'),
  ('woes', 'NNS'),
  ('-', ':'),
  ('entry', 'NN'),
  ('139.81', 'CD'),
  ('stop', 'NN'),
  ('131.92', 'CD')],
 [('SK', 'NNP'), ('GAVE', 'NNP'), ('!', '.')],
 [('ovti', 'JJ'),
  ('ttm', 'NN'),
  ('ending', 'VBG'),
  ('Oct', 'NNP'),
  ('2012', 'CD'),
  ('Negative', 'NNP'),
  ('151', 'CD'),
  ('million', 'CD'),
  ('operational', 'JJ'),
  ('cash', 'NN'),
  ('flow', 'NN'),
  ('..', 'VBD'),
  ('273', 'CD'),
  ('%', 'NN'),
  ('decline', 'NN'),
  ('vs', 'NN'),
  ('yoy', 'NN'),
  ('ttm', 'NN'),
  ('ending', 'VBG'),
  ('oct', 'JJ'),
  ('2011', 'CD')],
 [('AAP', 'NNP'),
  ('GOOG', 'NNP'),
  ('respond', 'NN'),
  ('positively', 'RB'),
  ('good', 'JJ'),
  ('jobless', 'NN'),
  ('claims', 'NNS'),
  ('numbers', 'NNS')],
 [('Analyst', 'NNP'),
  ('price', 'NN'),
  ('targets', 'NNS'),
  ('earnings', 'NNS'),
  ('targets', 'NNS'),
  ('coming', 'VBG'),
  ('--', ':'),
  ('-EXACTY', 'NN'),
  ('want', 'VBP'),
  ('see', 'NN'),
  ('prior', 'RB'),
  ('AAP', 'NNP'),
  ('reporting', 'NN'),
  ('.', '.')],
 [('user', 'JJ'),
  ('Nice', 'NNP'),
  ('!', '.'),
  ('Color', 'NNP'),
  ('INTC', 'NNP'),
  ('bull', 'NN'),
  ('well', 'RB'),
  ('!', '.')],
 [('Heads', 'NNS'),
  ('p', 'NNS'),
  (':', ':'),
  ('AA', 'NNP'),
  ('Earnings', 'NNP'),
  ('(', '('),
  ('1/8/13', 'CD'),
  (')', ')'),
  ('ess', 'NN'),
  ('Than', 'NNP'),
  ('Week', 'NNP'),
  ('Away', 'NNP'),
  (',', ','),
  ('Tho', 'NNP'),
  ('The', 'DT'),
  ('Season', 'NNP'),
  ('Does', 'NNP'),
  ("n't", 'RB'),
  ('EAY', 'NNP'),
  ('Begin', 'NNP'),
  ('Cranking', 'NNP'),
  ("'Til", 'POS'),
  ('1/16', 'CD'),
  ('w/', 'NN'),
  ('GS', 'NNP'),
  ('JPM', 'NNP'),
  ('EBAY', 'NNP'),
  ('et', 'FW'),
  ('al', 'NN'),
  ('...', ':')],
 [('trade', 'NN'),
  ('idea', 'NN'),
  ('buy', 'VB'),
  ('WO', 'NNP'),
  ('market', 'NN'),
  ('26.64', 'CD'),
  (',', ','),
  ('target', 'NN'),
  ('36', 'CD'),
  (',', ','),
  ('cut', 'VBD'),
  ('23.50', 'CD')],
 [('Trade', 'NNP'),
  ('idea', 'NN'),
  ('buy', 'VB'),
  ('DC', 'NNP'),
  ('market', 'NN'),
  ('58.50', 'CD'),
  (',', ','),
  ('target', 'NN'),
  ('67', 'CD'),
  (',', ','),
  ('cut', 'VBD'),
  ('53', 'CD')],
 [('GOOG', 'NNP'),
  ('looks', 'VBZ'),
  ('set', 'VBN'),
  ('make', 'VB'),
  ('new', 'JJ'),
  ('ATH', 'NNP'),
  ('.', '.'),
  ('Now', 'RB'),
  ('E', 'NNP'),
  ('unknown', 'JJ'),
  ('.', '.')],
 [('GOOG', 'NNP'),
  ('trade', 'NN'),
  ('one', 'CD'),
  ('long', 'JJ'),
  ('verse', 'NN'),
  ('10sma', 'CD')],
 [('FNF', 'NNP'),
  ('-', ':'),
  ('ong', 'RB'),
  ('19.43', 'CD'),
  ('.', '.'),
  ('Trailing', 'VBG'),
  ('Stop', 'NNP'),
  ('21.04', 'CD'),
  ('6', 'CD'),
  ('prior', 'JJ'),
  ('Stops', 'NNP'),
  ('19.71', 'CD'),
  (',', ','),
  ('19.52', 'CD'),
  (',', ','),
  ('18.70', 'CD'),
  (',', ','),
  ('18.65', 'CD'),
  (',', ','),
  ('18.07', 'CD'),
  ('17.87', 'CD'),
  ('-', ':')],
 [('FOD', 'NNP'),
  ('see', 'VBP'),
  ('solid', 'JJ'),
  ('move', 'NN'),
  ('tom', 'NN'),
  (',', ','),
  ('system', 'NN'),
  ('predict', 'JJ'),
  ('nice', 'RB'),
  ('green', 'JJ'),
  ('candle', 'NN'),
  ('.', '.')],
 [('This', 'DT'),
  ('year', 'NN'),
  ('fitness', 'NN'),
  ('health', 'NN'),
  ('apps', 'NN'),
  ('...', ':'),
  ('winners', 'NNS'),
  ('gynormous', 'JJ'),
  ('speculation', 'NN'),
  ('run', 'VBN'),
  ('high', 'JJ'),
  ('nke', 'NN')],
 [('It', 'PRP'),
  ("'s", 'VBZ'),
  ('time', 'NN'),
  ('invest', 'JJ'),
  ('MSFT', 'NNP'),
  ('COMPQ', 'NNP')],
 [('New', 'NNP'),
  ('Post', 'NNP'),
  (':', ':'),
  ('Shorts', 'NNS'),
  ('Will', 'MD'),
  ('Make', 'VB'),
  ('Dimes', 'NNP'),
  (',', ','),
  ('ongs', 'NNS'),
  ('Will', 'NNP'),
  ('Make', 'NNP'),
  ('Dollars', 'NNP'),
  ('AAP', 'NNP'),
  ('SPX', 'NNP'),
  ('QQQ', 'NNP'),
  ('P', 'NNP')],
 [('nbelieveable', 'JJ'),
  ('payment', 'NN'),
  ('trend', 'NN'),
  ('VC', 'NNP'),
  ("'s", 'POS'),
  ('chasing', 'VBG'),
  ('easily', 'RB'),
  ('played', 'VBN'),
  ('public', 'NN'),
  ('markets', 'NNS'),
  ('....', 'VBP'),
  ('EBAY', 'NNP'),
  ('V', 'NNP'),
  ('Mastercard', 'NNP'),
  ('MA', 'NNP'),
  ('time', 'NN'),
  ('highs', 'NNS')],
 [('Some', 'DT'),
  ('watch', 'VBP'),
  ('list', 'NN'),
  ('stocks', 'NNS'),
  ('triggered', 'VBD'),
  ('today', 'NN'),
  ('OEX', 'NNP'),
  ('AGNX', 'NNP'),
  ('TV', 'NNP'),
  ('VBD', 'NNP'),
  ('XIDE', 'NNP'),
  ('PPC', 'NNP'),
  ('EXP', 'NNP'),
  ('ONTY', 'NNP'),
  ('BMN', 'NNP'),
  ('FS', 'NNP'),
  ('WK', 'NNP'),
  ('CHMT', 'NNP'),
  ('FBC', 'NNP'),
  ('ISI', 'NNP'),
  ('AIG', 'NNP')],
 [('Nice', 'NNP'),
  ('Bull', 'NNP'),
  ('flag', 'NN'),
  ('breakout', 'NN'),
  ('OC', 'NNP'),
  ('#', '#'),
  ('technology', 'NN'),
  ('#', '#'),
  ('software', 'NN')],
 [('My', 'PRP$'),
  ('setup', 'NN'),
  ('alerts', 'NNS'),
  ('went', 'VBD'),
  ('bonkers', 'NNS'),
  ('today', 'NN'),
  ('..', 'VBP'),
  ('One', 'CD'),
  ('many', 'JJ'),
  ('got', 'VBD'),
  ('triggered.Cup+Handle', 'JJ'),
  ('breakout', 'IN'),
  ('PFE', 'NNP')],
 [('The', 'DT'),
  ('host', 'NN'),
  ('....', 'NNP'),
  ('congrats', 'VBZ'),
  ('cloud', 'VBP'),
  ('today', 'NN'),
  ('AX', 'NNP'),
  ('user', 'RB'),
  ('all-time', 'JJ'),
  ('highs', 'NNS'),
  ('.', '.'),
  ('wow', 'NN')],
 [('X', 'NN'),
  ('Did', 'NNP'),
  ('.S', 'NNP'),
  ('.', '.'),
  ('Steel', 'NNP'),
  ('Just', 'NNP'),
  ('Breakout', 'NNP'),
  ('?', '.'),
  ('MT', 'NNP')],
 [('DNDN', 'NNP'),
  ('broken', 'VBD'),
  ('clear', 'JJ'),
  ('5.5', 'CD'),
  ('resistanc', 'NN'),
  ('level', 'NN'),
  ('heavy', 'JJ'),
  ('volume', 'NN'),
  ('&', 'CC'),
  ('could', 'MD'),
  ('headed', 'VB'),
  ('much', 'RB'),
  ('higher', 'JJR')],
 [('EXPE', 'NNP'),
  ('looks', 'VBZ'),
  ('good', 'JJ'),
  ('higher', 'JJR'),
  ('prices', 'NNS')],
 [('apc', 'JJ'),
  ('weekly', 'JJ'),
  ('setting', 'NN'),
  ('long', 'RB'),
  ('.', '.')],
 [('I', 'PRP'),
  ('going', 'VBG'),
  ('morning', 'NN'),
  ('long', 'RB'),
  ('3', 'CD'),
  ('AAP', 'NNP'),
  ('560', 'CD'),
  ('call', 'NN'),
  ('options', 'NNS'),
  ('&', 'CC'),
  ('GOOG', 'NNP'),
  ('725', 'CD'),
  ('calls', 'VBZ'),
  ('Jan', 'NNP'),
  ('4th', 'CD'),
  ('expiration', 'NN')],
 [('ES_F', 'NNP'),
  ('path', 'NN'),
  ('higher', 'NN'),
  ('unthreatened', 'VBD'),
  ('unless', 'IN'),
  ('1452.25', 'CD'),
  ('support', 'NN'),
  ('fails', 'NNS'),
  ('.', '.'),
  ('See', 'VB'),
  ('resistance', 'NN'),
  ('1466.00', 'CD'),
  ('SPX', 'NNP'),
  ('#', '#'),
  ('stocks', 'NNS'),
  ('.', '.')],
 [('Monitor', 'NNP'),
  ('S', 'NNP'),
  ('line/price', 'NN'),
  ('dynamic', 'NN'),
  ('.', '.'),
  ('Stocks', 'NNS'),
  ('closed', 'VBD'),
  ('Dec.28', 'NNP'),
  ('S', 'NNP'),
  ('line', 'NN'),
  ('new', 'JJ'),
  ('highs', 'NNS'),
  ('be4', 'JJ'),
  ('price', 'NN'),
  ('.', '.'),
  ('MHO', 'NNP'),
  ('TSM', 'NNP'),
  ('IPGP', 'NNP'),
  ('EQIX', 'NNP'),
  ('BC', 'NNP'),
  ('BDC', 'NNP'),
  ('ASH', 'NNP')],
 [('DDD', 'NNP'), ('IDCC', 'NNP'), ('continue', 'VBP'), ('higher', 'JJR')],
 [('Had', 'NNP'),
  ('hoped', 'VBN'),
  ('pick', 'NN'),
  ('OST', 'NNP'),
  ('today', 'NN'),
  (',', ','),
  ('looks', 'VBZ'),
  ('like', 'IN'),
  ('I', 'PRP'),
  ("'m", 'VBP'),
  ('day', 'NN'),
  ('late', 'RB'),

In [97]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')
lemmatizer=WordNetLemmatizer()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\mehna\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\mehna\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [98]:
from nltk.corpus import wordnet

def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    elif treebank_tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN  # Default to NOUN if POS tag is unknown

In [99]:
pos_token[0][0]

('Kickers', 'NNS')

In [100]:
get_wordnet_pos(pos_token[0][0][1])

'n'

In [101]:
lem_data = []
for x in range(len(pos_token)):
  lem = [lemmatizer.lemmatize(pos_token[x][i][0],get_wordnet_pos(pos_token[x][i][1])) for i in range(len(pos_token[x]))]
  lem_data.append(lem)

In [102]:
lem_data

[['Kickers',
  'watchlist',
  'XIDE',
  'TIT',
  'SOQ',
  'PNK',
  'CPW',
  'BPZ',
  'AJ',
  'trade',
  'method',
  '1',
  'method',
  '2',
  ',',
  'see',
  'prev',
  'post'],
 ['user',
  ':',
  'AAP',
  'MOVIE',
  '.',
  '55',
  '%',
  'return',
  'FEA/GEED',
  'indicator',
  '15',
  'trade',
  'year',
  '.',
  'AWESOME',
  '.'],
 ['user',
  'I',
  "'d",
  'afraid',
  'short',
  'AMZN',
  '-',
  'look',
  'like',
  'near-monopoly',
  'eBooks',
  'infrastructure-as-a-service'],
 ['MNTA', 'Over', '12.00'],
 ['OI', 'Over', '21.37'],
 ['PGNX', 'Over', '3.04'],
 ['AAP',
  '-',
  'user',
  'current',
  'downtrend',
  'break',
  '.',
  'Otherwise',
  'short-term',
  'correction',
  'med-term',
  'downtrend',
  '.'],
 ['Monday',
  "'s",
  'relative',
  'weakness',
  '.',
  'NYX',
  'WIN',
  'TIE',
  'TAP',
  'ICE',
  'INT',
  'BMC',
  'AON',
  'C',
  'CHK',
  'BIIB'],
 ['GOOG',
  '-',
  'ower',
  'trend',
  'line',
  'channel',
  'test',
  '&',
  'volume',
  'support',
  '.'],
 ['AAP', 'watch', 'tomorrow', 'ONG', 'entry', '.'],
 ["'m",
  'assume',
  'FCX',
  'open',
  'tomorrow',
  '34.25',
  'trigger',
  'buy',
  '.',
  'still',
  'much',
  'like',
  'setup',
  '.'],
 ['It',
  'really',
  'worry',
  'everyone',
  'expect',
  'market',
  'rally',
  ',',
  'usually',
  'exact',
  'opposite',
  'happens',
  'every',
  'time',
  'shall',
  'see',
  'soon',
  'bac',
  'spx',
  'jpm'],
 ['AAP',
  'GAMCO',
  "'s",
  'arry',
  'Haverty',
  ':',
  'Apple',
  'Is',
  'Extremely',
  'Cheap',
  'Great',
  'Video',
  '!',
  '!',
  '!'],
 ['user',
  'Maykiljil',
  'post',
  '.',
  'I',
  'agree',
  'MSFT',
  'go',
  'high',
  '&',
  'possibly',
  'north',
  '30'],
 ['Momentum',
  'come',
  'back',
  'ETFC',
  'Broke',
  'MA200',
  'resistance',
  'solid',
  'volume',
  'Friday',
  '.',
  'ong',
  'set-up'],
 ['HA', 'Hitting', '35.65', 'mean', 'resume', 'target', '42', 'level', '..'],
 ['user',
  'gameplan',
  'shot',
  'today',
  'I',
  'like',
  'trend',
  'break',
  'May',
  'c+h',
  'break',
  '.',
  'OC',
  'weekly',
  'trend',
  'break',
  'back',
  'july',
  '2011'],
 ['FCX',
  'gap',
  'well',
  'ideal',
  'entry',
  'look',
  'pull',
  'least',
  '35',
  'open',
  'entry'],
 ['user',
  'great',
  'list',
  ',',
  'particularly',
  'like',
  'FISV',
  'SYK',
  '.',
  'All',
  'buy',
  '&',
  'hold',
  'type',
  'check',
  'free',
  'list',
  '.'],
 ['ATHX', 'upper', 'trend', 'line'],
 ['NG',
  '-',
  'nice',
  'PNF',
  'BY',
  '-',
  'breakout',
  '-',
  'need',
  'follow',
  'thru'],
 ['Wo',
  "n't",
  'believe',
  'AAP',
  'uptrend',
  'back',
  'cross',
  'MA',
  '(',
  '50',
  ')'],
 ['X', 'swing', 'still'],
 ['SWY', '-', '30', '%', 'float', 'short', 'break', '-', 'ouch'],
 ['BIOF', 'want', '4.90', "'s", 'comin', '!', '!', '!'],
 ['VS',
  'invert',
  'head',
  'shoulder',
  'play',
  'well',
  '.',
  'Was',
  "n't",
  'able',
  'catch',
  'entry',
  '.',
  'Eyes'],
 ['red', ',', 'ready', 'break', '.'],
 ['EI', 'close', 'break', '.', 'My', 'trigger', '30.40', '.'],
 ['user',
  'BAC',
  'For',
  'quick',
  'Trade',
  'late',
  '..',
  'But',
  'invest',
  '~11.98',
  'good',
  'entry',
  'point',
  'IMHO'],
 ['CHDN',
  '-',
  'ong',
  '49.02',
  '.',
  'Trailing',
  'Stop',
  '56.66',
  '6',
  'prior',
  'Stops',
  '54.17',
  ',',
  '49.88',
  ',',
  '49.82',
  ',',
  '45.47',
  ',',
  '43.02',
  '&',
  '41.92',
  '-'],
 ['AAP',
  'VOME',
  'today',
  'impressive',
  '.',
  'At',
  'rate',
  'well',
  'probably',
  'get',
  '30M',
  'share',
  'trade',
  'today',
  '.'],
 ['user',
  ':',
  'add',
  'VXY',
  'long',
  'bottom',
  'today',
  'trade',
  ',',
  'also',
  'get',
  'WPI',
  'near',
  'low'],
 ['I',
  'repeat',
  ',',
  'global',
  'economy',
  'go',
  'get',
  'good',
  'year',
  'go',
  'C',
  'instead',
  'BAC'],
 ['GOOG', 'go', 'ONG', 'close', '725', '.'],
 ['NKD',
  'look',
  'like',
  'good',
  'short',
  '.',
  'Failed',
  'break',
  'price',
  'level',
  'resistance',
  '116',
  'today',
  '.'],
 ['GS',
  'like',
  'price',
  'action',
  '.',
  'So',
  'far',
  'hold',
  '130',
  '.',
  'Still',
  'decide',
  'whether',
  'go',
  'ONG',
  'call',
  'stock',
  '.'],
 ['SBX', 'buy', 'clear', 'resistance', '54.5'],
 ['NEW',
  'target',
  'AAP',
  'notice',
  'shakeout',
  'read',
  '-8.49',
  '!',
  'buy',
  'dot',
  'Monday'],
 ['Too',
  'early',
  'short',
  'move',
  '.',
  'Stock',
  'Market',
  'need',
  'day',
  'settle',
  '.',
  '#',
  'Patience',
  'COH',
  'BWD',
  'DT',
  'AAP',
  'PAY'],
 ['AAP',
  'obbers',
  'hit',
  'Apple',
  'Store',
  'Paris',
  '.',
  'Prefer',
  'take',
  'merchendise',
  'cash',
  '.',
  'Bullish',
  '.'],
 ['AXA',
  'Here',
  'tip',
  'day',
  '.',
  'Buy',
  '!',
  'You',
  'even',
  'sign',
  'newsletter',
  'anything',
  'O',
  'If',
  'I',
  "'m",
  'wrong',
  'I',
  'eat',
  'crow',
  ':',
  ')'],
 ['X',
  '1/2',
  'due',
  'move',
  'today',
  'Kirby',
  'daily',
  'around',
  '26.00',
  '-',
  'still',
  'swing',
  '1/2'],
 ['AAP',
  '10',
  'min',
  'short',
  'longs',
  'fully',
  'add',
  ',',
  'look',
  'pop',
  'market',
  ',',
  'shakeout',
  'reset'],
 ['NG',
  'stellar',
  'move',
  '-',
  'still',
  'long',
  'swing',
  '-',
  'full',
  'position',
  '-',
  'I',
  'believe',
  'user',
  '&',
  'user',
  '2'],
 ['ATICE', '&', 'TADE', 'SETP', ':', 'KO', 'AN', 'CNX'],
 ['IDCC',
  '50SMA',
  'act',
  'good',
  'support',
  '.',
  'Short-term',
  'momentum',
  'indicator',
  'switch',
  'upside',
  '.'],
 ['NEW',
  'POST',
  ':',
  'BAC',
  'Is',
  'At',
  '19',
  'Month',
  'Highs',
  ',',
  'But',
  'Showing',
  'Signs',
  'Stress'],
 ['c', 'two', 'daily', 'bull', 'flag', 'top', 'other=bullish', 'still'],
 ['NG',
  '-',
  'traditional',
  'AT',
  'point',
  'figure',
  '-',
  'bullish',
  'BY',
  'signal',
  'multiyear',
  'high'],
 ['jpm',
  'close',
  '>',
  '10sma',
  'Monday',
  '(',
  'u',
  'know',
  'rule',
  ')',
  '...',
  'large',
  'cup',
  'n',
  'handle',
  '....',
  'still',
  'bullish'],
 ['EOG',
  'ascend',
  'triangle',
  '-',
  'original',
  'target',
  '127',
  'extension',
  'EPS',
  'Feb',
  '11th',
  '?',
  '1/2',
  'position',
  'swing'],
 ['aapl',
  'daily',
  ',',
  'break',
  'downtrend',
  '(',
  'close',
  'price',
  ')',
  'w',
  'v',
  'pattern',
  'back',
  'play',
  '.......',
  '600',
  'target'],
 ['PHM',
  'PulteGroup',
  'Option',
  'Bear',
  'bet',
  '1.5',
  'Million',
  '11',
  '%',
  'move',
  'April'],
 ['BAC', 'In', '11.97', 'trade'],
 ['Short',
  'Setups',
  'display',
  'relative',
  'weakness',
  ':',
  'AO',
  'COH',
  'PAY',
  'BWD',
  'DT',
  'SHD',
  'WTW',
  'P',
  'Prepare',
  'short',
  'stall',
  '.',
  'ES_F'],
 ['When',
  'AMZN',
  'monetize',
  'electronics',
  'make',
  'traffic',
  'marketplace',
  ',',
  'AAP',
  'GOOG',
  'wake',
  'say',
  "n't",
  'buy',
  'EBAY'],
 ['CVI',
  'start',
  'clean',
  'book',
  ',',
  'make',
  'first',
  'buy',
  'yr',
  '-',
  'entry',
  '49.54',
  'stop',
  '47.43'],
 ['SAM',
  'cheer',
  'temporary',
  'solution',
  'economic',
  'woe',
  '-',
  'entry',
  '139.81',
  'stop',
  '131.92'],
 ['SK', 'GAVE', '!'],
 ['ovti',
  'ttm',
  'end',
  'Oct',
  '2012',
  'Negative',
  '151',
  'million',
  'operational',
  'cash',
  'flow',
  '..',
  '273',
  '%',
  'decline',
  'v',
  'yoy',
  'ttm',
  'end',
  'oct',
  '2011'],
 ['AAP',
  'GOOG',
  'respond',
  'positively',
  'good',
  'jobless',
  'claim',
  'number'],
 ['Analyst',
  'price',
  'target',
  'earnings',
  'target',
  'come',
  '--',
  '-EXACTY',
  'want',
  'see',
  'prior',
  'AAP',
  'reporting',
  '.'],
 ['user', 'Nice', '!', 'Color', 'INTC', 'bull', 'well', '!'],
 ['Heads',
  'p',
  ':',
  'AA',
  'Earnings',
  '(',
  '1/8/13',
  ')',
  'es',
  'Than',
  'Week',
  'Away',
  ',',
  'Tho',
  'The',
  'Season',
  'Does',
  "n't",
  'EAY',
  'Begin',
  'Cranking',
  "'Til",
  '1/16',
  'w/',
  'GS',
  'JPM',
  'EBAY',
  'et',
  'al',
  '...'],
 ['trade',
  'idea',
  'buy',
  'WO',
  'market',
  '26.64',
  ',',
  'target',
  '36',
  ',',
  'cut',
  '23.50'],
 ['Trade',
  'idea',
  'buy',
  'DC',
  'market',
  '58.50',
  ',',
  'target',
  '67',
  ',',
  'cut',
  '53'],
 ['GOOG',
  'look',
  'set',
  'make',
  'new',
  'ATH',
  '.',
  'Now',
  'E',
  'unknown',
  '.'],
 ['GOOG', 'trade', 'one', 'long', 'verse', '10sma'],
 ['FNF',
  '-',
  'ong',
  '19.43',
  '.',
  'Trailing',
  'Stop',
  '21.04',
  '6',
  'prior',
  'Stops',
  '19.71',
  ',',
  '19.52',
  ',',
  '18.70',
  ',',
  '18.65',
  ',',
  '18.07',
  '17.87',
  '-'],
 ['FOD',
  'see',
  'solid',
  'move',
  'tom',
  ',',
  'system',
  'predict',
  'nice',
  'green',
  'candle',
  '.'],
 ['This',
  'year',
  'fitness',
  'health',
  'apps',
  '...',
  'winner',
  'gynormous',
  'speculation',
  'run',
  'high',
  'nke'],
 ['It', "'s", 'time', 'invest', 'MSFT', 'COMPQ'],
 ['New',
  'Post',
  ':',
  'Shorts',
  'Will',
  'Make',
  'Dimes',
  ',',
  'ongs',
  'Will',
  'Make',
  'Dollars',
  'AAP',
  'SPX',
  'QQQ',
  'P'],
 ['nbelieveable',
  'payment',
  'trend',
  'VC',
  "'s",
  'chase',
  'easily',
  'play',
  'public',
  'market',
  '....',
  'EBAY',
  'V',
  'Mastercard',
  'MA',
  'time',
  'high'],
 ['Some',
  'watch',
  'list',
  'stock',
  'trigger',
  'today',
  'OEX',
  'AGNX',
  'TV',
  'VBD',
  'XIDE',
  'PPC',
  'EXP',
  'ONTY',
  'BMN',
  'FS',
  'WK',
  'CHMT',
  'FBC',
  'ISI',
  'AIG'],
 ['Nice',
  'Bull',
  'flag',
  'breakout',
  'OC',
  '#',
  'technology',
  '#',
  'software'],
 ['My',
  'setup',
  'alert',
  'go',
  'bonkers',
  'today',
  '..',
  'One',
  'many',
  'get',
  'triggered.Cup+Handle',
  'breakout',
  'PFE'],
 ['The',
  'host',
  '....',
  'congrats',
  'cloud',
  'today',
  'AX',
  'user',
  'all-time',
  'high',
  '.',
  'wow'],
 ['X', 'Did', '.S', '.', 'Steel', 'Just', 'Breakout', '?', 'MT'],
 ['DNDN',
  'break',
  'clear',
  '5.5',
  'resistanc',
  'level',
  'heavy',
  'volume',
  '&',
  'could',
  'head',
  'much',
  'high'],
 ['EXPE', 'look', 'good', 'high', 'price'],
 ['apc', 'weekly', 'setting', 'long', '.'],
 ['I',
  'go',
  'morning',
  'long',
  '3',
  'AAP',
  '560',
  'call',
  'option',
  '&',
  'GOOG',
  '725',
  'call',
  'Jan',
  '4th',
  'expiration'],
 ['ES_F',
  'path',
  'higher',
  'unthreatened',
  'unless',
  '1452.25',
  'support',
  'fails',
  '.',
  'See',
  'resistance',
  '1466.00',
  'SPX',
  '#',
  'stock',
  '.'],
 ['Monitor',
  'S',
  'line/price',
  'dynamic',
  '.',
  'Stocks',
  'close',
  'Dec.28',
  'S',
  'line',
  'new',
  'high',
  'be4',
  'price',
  '.',
  'MHO',
  'TSM',
  'IPGP',
  'EQIX',
  'BC',
  'BDC',
  'ASH'],
 ['DDD', 'IDCC', 'continue', 'high'],
 ['Had',
  'hop',
  'pick',
  'OST',
  'today',
  ',',
  'look',
  'like',
  'I',
  "'m",
  'day',
  'late',
  '.',
  'Nice',
  'move',
  'morning',
  '.'],
 ['GPS', 'wow', 'wa', 'fast', 'fast', 'fade', '...'],
 ['AMZN',
  'go',
  '260',
  '.',
  'Should',
  'go',
  'near',
  '300',
  'market',
  'behaves',
  'week',
  '.'],
 ['Huston', 'GEEN', 'AAP'],
 ['P', 'long', '9.55'],
 ['HN',
  'breakout',
  '...',
  '3rd',
  'day',
  'look',
  'pullback',
  'enter',
  'long',
  '.'],
 ['NG',
  '-',
  'ascend',
  'triangle',
  'much',
  'like',
  'FS',
  '&',
  'X',
  'breakouts',
  '127',
  'exten',
  '161.8',
  'target',
  '-',
  'fib',
  'subjective'],
 ['KCG', '...', 'thing', 'make', 'go', 'hmmmm', '?'],
 ['VNG', '-', 'Huge', 'news', 'patent', 'attorney', 'Dan', 'avicher'],
 ['NG',
  'nhod',
  '-',
  'check',
  'weekly',
  '-',
  'target',
  'previous',
  'low',
  '2006',
  ':',
  ')'],
 ['NG',
  'nhod',
  '-',
  'see',
  '?',
  'check',
  'weekly',
  '-',
  'target',
  'previous',
  'low',
  '2006',
  ':',
  ')'],
 ['AIG',
  'American',
  'International',
  'Group',
  'Option',
  'Traders',
  'bet',
  '4',
  '%',
  'move',
  'next',
  'Friday'],
 ['P', 'balance', '+.32'],
 ['VNG', 'buy', 'vs.', 'Sells', '?'],
 ['BAC',
  'In',
  '12.00',
  'since',
  'consolidation',
  'level',
  '.',
  'We',
  'could',
  'close',
  '=',
  '>',
  '12.09',
  'market',
  'stable',
  'pm',
  'IMHO',
  '.'],
 ['VNG', 'Parabolic', 'move', 'comin', "'"],
 ['New',
  'Sony',
  'pre-owned',
  'block',
  'tech',
  'patent',
  'unearth',
  'SNE',
  '...',
  '50',
  '%',
  'GME',
  'profit',
  'pre',
  'own',
  '..',
  'last',
  'one',
  'turn',
  'light'],
 ['like',
  'VS',
  ',',
  'love',
  'WYNN',
  '111',
  'entry',
  'new',
  'target',
  'yesterday',
  '121.',
  'nice',
  '!'],
 ['user',
  ':',
  'SPX',
  '1464.90',
  'Wave',
  'iv',
  'would',
  '20',
  'point',
  'low',
  '[',
  '1467.00',
  'KEY',
  ']',
  'ES_F',
  'HOD',
  '1460.00',
  '(',
  'neckline',
  '1458.50',
  'bearish',
  ')'],
 ['DDD',
  'consolidate',
  'strong',
  'move',
  'previous',
  'day',
  '55',
  '60',
  ',',
  'next',
  'buy',
  'point',
  '60',
  'volume',
  '(',
  'hold',
  ')',
  '.'],
 ['VNG',
  '-',
  '12',
  'mil',
  'share',
  'short',
  'plus',
  'long',
  'buying',
  '=',
  'massive',
  'VNG',
  'short',
  'squeeze',
  '.',
  'Just',
  'think',
  'story',
  'dead',
  'avicher',
  'kill',
  'short',
  'thesis'],
 ['Wow',
  ',',
  'good',
  'BKS',
  'T',
  'user',
  '...',
  'sale',
  'Nook',
  '13',
  '%',
  'holiday'],
 ['AC',
  'watch',
  'list',
  '-',
  'volume',
  'pick',
  '139',
  '%',
  'full',
  'day',
  'average',
  '-from',
  '200-day',
  'bounce'],
 ['The',
  'new',
  'wightwatchers',
  'ad',
  'fun',
  'light',
  'regular',
  'people',
  'interest',
  ',',
  'I',
  'still',
  'dont',
  'trust',
  'WTW',
  '(',
  'position',
  ')'],
 ['AMZN',
  'hold',
  'well',
  '-',
  'next',
  'buy',
  'point',
  'clear',
  'upper',
  'trend',
  'line',
  'heavy',
  'volume'],
 ['MA',
  'exactly',
  'want',
  'see',
  'follow',
  'thru',
  'day',
  'break',
  'new',
  'high',
  'volume'],
 ['ZCS', 'user', 'There', "'s", 'buying'],
 ['AAP', 'SPY', 'QE', '2013', '.', 'Now', 'bring', 'Geithner', '.'],
 ['Over',
  'extended',
  'stock',
  'market',
  '+',
  'unexpected',
  'news',
  'FED',
  'minute',
  '=',
  'Down',
  'ESD',
  '&',
  'panicky',
  'ES_F',
  'NQ_F',
  '.'],
 ['SPY',
  'ncle',
  'Ben',
  'need',
  'spice',
  'thing',
  'little',
  '.',
  'AAP',
  'people',
  'bore',
  ',',
  'wake',
  '.'],
 ['AAP',
  'might',
  'close',
  'low',
  'day',
  '.',
  'Bears',
  'control',
  'descend',
  'trendline',
  '.',
  'Watch',
  '.'],
 ['FAN',
  '-',
  'seek',
  '200d',
  '.',
  'Im',
  'add',
  'synthetic',
  'short',
  'add',
  '200d',
  '.'],
 ['CWST',
  'low',
  'day',
  '4.50',
  ',',
  'near',
  'high',
  'day',
  '4.56',
  ',',
  'watchn',
  'b/out',
  ',',
  'minimal',
  'risk'],
 ['All', ':', 'gme', 'Gamestop', 'short', 'target', 'spy'],
 ['time', 'get', '#', 'cloud', 'stock', 'VMW', 'CM'],
 ['BAC',
  'Keep',
  'Overniight',
  'mmy',
  'po',
  '.',
  'bin',
  'premarket',
  'Tmorrow',
  '.'],
 ['Polk',
  'Expects',
  '2013',
  '.S',
  '.',
  'New',
  'Vehicle',
  'egistrations',
  '15.3',
  'Million',
  '-',
  'Polk',
  '-',
  'F',
  'GM',
  'I',
  'think',
  'low'],
 ['Very',
  'bullish',
  'market',
  'also',
  'talk',
  'trend',
  'SCTY',
  'OST',
  'ANGI',
  'FIO',
  'PANW',
  'A',
  'JCP',
  'P',
  'YEP',
  'MNST',
  'GPN',
  'show',
  '.'],
 ['BAC', 'happen', 'next', '?'],
 ['KCG', 'someone', 'buy', '3.22k', '4', 'Jan', '18', 'Calls', '....'],
 ['Man',
  'I',
  'didnt',
  'know',
  'Skippy',
  'I',
  'make',
  '...',
  'would',
  'throw',
  'jar',
  'H',
  '#',
  'Hormel'],
 ['Big',
  'move',
  'bond',
  'today',
  ',',
  '7',
  'month',
  'high',
  '10',
  'rate',
  ',',
  'still',
  'go',
  'lower',
  'ZN_F',
  ',',
  'could',
  'get',
  'truly',
  'ugly',
  'good',
  'NFP',
  'number',
  'AM',
  'SPY',
  'TT'],
 ['Market',
  'Wrap',
  'Video',
  '+',
  'Additions',
  'Watch',
  'ist',
  'include',
  ':',
  'BCEI',
  'BJI',
  'CEE',
  'ES',
  'SONS',
  'SQNM',
  'NX',
  'YEP'],
 ['Maybe',
  'vrng',
  'ask',
  'judge',
  '7',
  '%',
  'royalty',
  'become',
  'risky',
  'goog',
  'deal',
  '?',
  'want',
  'settle'],
 ['BJI', 'Over', '35.53', 'good', 'volume'],
 ['CEE', 'Over', '35.12'],
 ['SQNM', 'Over', '5.05'],
 ['NX', 'On', 'flag', 'break'],
 ['3D',
  'Systems',
  'Brings',
  'Next-Gen',
  'Consumer',
  '3D',
  'Printing',
  'CES',
  '2013',
  'DDD'],
 ['AAP',
  'top',
  'April',
  'Aston',
  'Kutcher',
  'star',
  "'jOBS",
  "'",
  '.',
  'Kinda',
  'like',
  'Facebook',
  "'Social",
  'Network',
  "'",
  'come',
  '.',
  'FB'],
 ['VNG',
  'w/',
  'MACD',
  'turn',
  '&',
  'signal',
  'line',
  ',',
  'VNG',
  'could',
  'post',
  'nice',
  'rally',
  'current',
  'level'],
 ['PI',
  '3Q',
  '10Q',
  'operational',
  'cash',
  'flow',
  '9mos',
  '-20million',
  '.',
  '269',
  '%',
  'decline',
  'vs.',
  '9mos',
  'year',
  'ago',
  '.'],
 ['bbby',
  '3Q',
  '10Q',
  'Operational',
  'Cash',
  'Flow',
  '135',
  'million',
  '.',
  '53',
  'increase',
  'vs.',
  'year',
  'ago',
  'Q3',
  '.',
  '64',
  '%',
  'improvement',
  'q',
  'q'],
 ['DI',
  '6mos',
  'operational',
  'cash',
  'flow',
  '267',
  'million',
  '.',
  'increase',
  '187',
  'million',
  'vs.6mos',
  'year',
  'ago',
  '.',
  '233',
  '%',
  'increase'],
 ['AM',
  '3Q',
  '10Q',
  '9mos',
  'operational',
  'cash',
  'flow',
  '32',
  'million',
  'vs.',
  'neg',
  '26',
  'mil',
  '9mos',
  'year',
  'ago',
  '.'],
 ['3Q',
  'operational',
  'cash',
  'flow',
  'neg',
  '16',
  'million',
  '.',
  'vs.',
  'year',
  'ago',
  '3Q',
  'negative',
  '68million',
  '.',
  '52',
  'million',
  'improvement'],
 ['A',
  'quiet',
  'Carl',
  'Icahn',
  '=',
  'Bullish',
  '.',
  'NFX',
  'short',
  'paranoid',
  'every',
  'close',
  'get',
  'acquire',
  '.',
  'Think',
  'aapl',
  ',',
  'msft',
  ',',
  'amzn',
  ',',
  'fb'],
 ['I', 'aapl', 'bull', 'break', 'trend', 'line', 'OBV'],
 ['user',
  'Phantom7',
  'I',
  "'ve",
  'call',
  '+4',
  'ever',
  'since',
  'start',
  'thing',
  '.',
  '3.75',
  'given~',
  'KCG'],
 ['NX',
  'watch',
  'list',
  'small',
  'flag',
  'volume',
  '26',
  '%',
  'ave',
  'full',
  'day',
  'good',
  'volume'],
 ['GOOG',
  'poise',
  'clear',
  'next',
  'resistance',
  '(',
  'buy',
  '/',
  'add',
  'area',
  ')',
  'watch',
  'action',
  '/',
  'volume',
  'closely'],
 ['GDP',
  'watch',
  'list',
  'slightly',
  'line',
  '50-day',
  'EMA',
  'light',
  'volume',
  '5',
  '%',
  'ave',
  'full',
  'day'],
 ['Took', 'profit', 'DDD', ',', 'add', 'break', '60', 'volume', '.'],
 ['CHK',
  '-',
  'I',
  "'m",
  'look',
  '-',
  'small',
  'risk',
  'position',
  'call',
  '.',
  'Scalp',
  '-',
  'maybe',
  'swing',
  'XE',
  'watch',
  '.'],
 ['ONTY',
  'If',
  'holder',
  'would',
  'hold',
  'raise',
  'ask',
  ',',
  'could',
  'really',
  'pop',
  '.',
  'Going',
  'climb',
  'slowly',
  'regardless',
  '...'],
 ['EOG', 'PXD', 'OAS', '#', 'energyswag'],
 ['AAP',
  'move',
  'volume',
  '.',
  'Couldnt',
  'cope',
  'descend',
  'trend',
  'line',
  '.',
  'Trend',
  'still',
  '.',
  'Perhaps',
  '460',
  'impossible',
  '.'],
 ['AAP',
  '50EMA',
  'continue',
  'work',
  'AAP',
  'make',
  'low',
  'high',
  'MACO',
  'sense'],
 ['Went',
  'short',
  'SPY',
  'yesterday',
  ',',
  'pick',
  'AAP',
  'instead',
  '.',
  'Still',
  'think',
  'market',
  'need',
  'move',
  'bit',
  'resume',
  'move',
  'upside',
  '.'],
 ['AAP',
  'people',
  'realistic',
  '.',
  'Market',
  'undecided',
  'apple',
  '.',
  'Earnings',
  'lift',
  'cloud',
  '.',
  'If',
  'GOOD',
  'might',
  'EAY',
  'see',
  'reversal',
  '.'],
 ['Will',
  'watch',
  'close',
  'carefully',
  'decide',
  'whether',
  'ONG',
  'SHOT',
  'AAP',
  '.',
  'Below',
  '530',
  'SHOT',
  '!',
  '!',
  '!'],
 ['JCP',
  'Keep',
  'eye',
  'triangle',
  '.',
  'big',
  'short',
  'int',
  ',',
  '34',
  '%',
  '.',
  'report',
  'Feb',
  '27.',
  'cup',
  '&',
  'handle',
  '.',
  'DT',
  '.',
  'ong'],
 ['sell', 'little', 'goog', '...', 'first', 'time'],
 ['Nice', 'cup', 'handle', 'breakout', 'MCA'],
 ['FAF', 'new', 'high', '.'],
 ['SPY', 'give', 'AAP', 'finger', '.', 'We', "n't", 'care', 'anymore', 'lol'],
 ['The', 'Smith', '&', 'Corona', 'ok.', 'AMZN'],
 ['VA',
  '-',

In [103]:
stem_vec=[' '.join(message) for message in stemedata]

In [104]:
stem_vec

['kicker watchlist xide tit soq pnk cpw bpz aj trade method 1 method 2 , see prev post',
 'user : aap movi . 55 % return fea/ge indic 15 trade year . awesom .',
 "user i 'd afraid short amzn - look like near-monopoli ebook infrastructure-as-a-servic",
 'mnta over 12.00',
 'oi over 21.37',
 'pgnx over 3.04',
 'aap - user current downtrend break . otherwis short-term correct med-term downtrend .',
 "monday 's rel weak . nyx win tie tap ice int bmc aon c chk biib",
 'goog - ower trend line channel test & volum support .',
 'aap watch tomorrow ong entri .',
 "'m assum fcx open tomorrow 34.25 trigger buy . still much like setup .",
 'it realli worri everyon expect market ralli , usual exact opposit happen everi time shall see soon bac spx jpm',
 "aap gamco 's arri haverti : appl is extrem cheap great video ! ! !",
 'user maykiljil post . i agre msft go higher & possibl north 30',
 'momentum come back etfc broke ma200 resist solid volum friday . ong set-up',
 'ha hit 35.65 mean resum target 42 level ..',
 'user gameplan shot today i like trend break may c+h break . oc weekli trend break back juli 2011',
 'fcx gap well ideal entri look pull least 35 open entri',
 'user great list , particularli like fisv syk . all buy & hold type check free list .',
 'athx upper trend line',
 'ng - nice pnf by - breakout - need follow thru',
 "wo n't believ aap uptrend back cross ma ( 50 )",
 'x swing still',
 'swi - 30 % float short break - ouch',
 "biof want 4.90 's comin ! ! !",
 "vs invert head shoulder play well . wa n't abl catch entri . eye",
 'red , readi break .',
 'ei close break . my trigger 30.40 .',
 'user bac for quick trade late .. but invest ~11.98 good entri point imho',
 'chdn - ong 49.02 . trail stop 56.66 6 prior stop 54.17 , 49.88 , 49.82 , 45.47 , 43.02 & 41.92 -',
 'aap vome today impress . at rate well probabl get 30m share trade today .',
 'user : ad vxi long bottom today trade , also got wpi near low',
 'i repeat , global economi go get better year go c instead bac',
 'goog go ong close 725 .',
 'nkd look like good short . fail break price level resist 116 today .',
 'gs like price action . so far hold 130 . still decid whether go ong call stock .',
 'sbx buy clear resist 54.5',
 'new target aap notic shakeout read -8.49 ! buy dot monday',
 'too earli short move . stock market need day settl . # patienc coh bwd dt aap pay',
 'aap obber hit appl store pari . prefer take merchendis cash . bullish .',
 "axa here tip day . buy ! you even sign newslett anyth o if i 'm wrong i eat crow : )",
 'x 1/2 due move today kirbi daili around 26.00 - still swing 1/2',
 'aap 10 min short long fulli ad , look pop market , shakeout reset',
 'ng stellar move - still long swing - full posit - i believ user & user 2',
 'atic & tade setp : ko an cnx',
 'idcc 50sma act good support . short-term momentum indic switch upsid .',
 'new post : bac is at 19 month high , but show sign stress',
 'c two daili bull flag top other=bullish still',
 'ng - tradit at point figur - bullish by signal multiyear high',
 'jpm close > 10sma monday ( u know rule ) ... larg cup n handl .... still bullish',
 'eog ascend triangl - origin target 127 extens ep feb 11th ? 1/2 posit swing',
 'aapl daili , broke downtrend ( close price ) w v pattern back play ....... 600 target',
 'phm pultegroup option bear bet 1.5 million 11 % move april',
 'bac in 11.97 trade',
 'short setup display rel weak : ao coh pay bwd dt shd wtw p prepar short stall . es_f',
 "when amzn monet electron make traffic marketplac , aap goog wake say n't buy ebay",
 'cvi start clean book , make first buy yr - entri 49.54 stop 47.43',
 'sam cheer temporari solut econom woe - entri 139.81 stop 131.92',
 'sk gave !',
 'ovti ttm end oct 2012 neg 151 million oper cash flow .. 273 % declin vs yoy ttm end oct 2011',
 'aap goog respond posit good jobless claim number',
 'analyst price target earn target come -- -exacti want see prior aap report .',
 'user nice ! color intc bull well !',
 "head p : aa earn ( 1/8/13 ) ess than week away , tho the season doe n't eay begin crank 'til 1/16 w/ gs jpm ebay et al ...",
 'trade idea buy wo market 26.64 , target 36 , cut 23.50',
 'trade idea buy dc market 58.50 , target 67 , cut 53',
 'goog look set make new ath . now e unknown .',
 'goog trade one long vers 10sma',
 'fnf - ong 19.43 . trail stop 21.04 6 prior stop 19.71 , 19.52 , 18.70 , 18.65 , 18.07 17.87 -',
 'fod see solid move tom , system predict nice green candl .',
 'thi year fit health app ... winner gynorm specul run high nke',
 "it 's time invest msft compq",
 'new post : short will make dime , ong will make dollar aap spx qqq p',
 "nbeliev payment trend vc 's chase easili play public market .... ebay v mastercard ma time high",
 'some watch list stock trigger today oex agnx tv vbd xide ppc exp onti bmn fs wk chmt fbc isi aig',
 'nice bull flag breakout oc # technolog # softwar',
 'my setup alert went bonker today .. one mani got triggered.cup+handl breakout pfe',
 'the host .... congrat cloud today ax user all-tim high . wow',
 'x did .s . steel just breakout ? mt',
 'dndn broken clear 5.5 resistanc level heavi volum & could head much higher',
 'exp look good higher price',
 'apc weekli set long .',
 'i go morn long 3 aap 560 call option & goog 725 call jan 4th expir',
 'es_f path higher unthreaten unless 1452.25 support fail . see resist 1466.00 spx # stock .',
 'monitor s line/pric dynam . stock close dec.28 s line new high be4 price . mho tsm ipgp eqix bc bdc ash',
 'ddd idcc continu higher',
 "had hope pick ost today , look like i 'm day late . nice move morn .",
 'gp wow wa fast fast fade ...',
 'amzn go 260 . should go near 300 market behav week .',
 'huston geen aap',
 'p long 9.55',
 'hn breakout ... 3rd day look pullback enter long .',
 'ng - ascend triangl much like fs & x breakout 127 exten 161.8 target - fib subject',
 'kcg ... thing make go hmmmm ?',
 'vng - huge news patent attorney dan avich',
 'ng nhod - check weekli - target previou low 2006 : )',
 'ng nhod - see ? check weekli - target previou low 2006 : )',
 'aig american intern group option trader bet 4 % move next friday',
 'p balanc +.32',
 'vng buy vs. sell ?',
 'bac in 12.00 sinc consolid level . we could close = > 12.09 market stabl pm imho .',
 "vng parabol move comin '",
 'new soni pre-own block tech patent unearth sne ... 50 % gme profit pre own .. last one turn light',
 'like vs , love wynn 111 entri new target yesterday 121. nice !',
 'user : spx 1464.90 wave iv would 20 point lower [ 1467.00 key ] es_f hod 1460.00 ( necklin 1458.50 bearish )',
 'ddd consolid strong move previou day 55 60 , next buy point 60 volum ( hold ) .',
 'vng - 12 mil share short plu long buy = massiv vng short squeez . just thought stori dead avich kill short thesi',
 'wow , good bk t user ... sale nook 13 % holiday',
 'ac watch list - volum pick 139 % full day averag -from 200-day bounc',
 'the new wightwatch ad fun light regular peopl interest , i still dont trust wtw ( posit )',
 'amzn hold well - next buy point clear upper trend line heavi volum',
 'ma exactli want see follow thru day break new high volum',
 "zc user there 's buy",
 'aap spi qe 2013 . now bring geithner .',
 'over extend stock market + unexpect news fed minut = down esd & panicki es_f nq_f .',
 'spi ncle ben need spice thing littl . aap peopl bore , wake .',
 'aap might close low day . bear control descend trendlin . watch .',
 'fan - seek 200d . im ad synthet short add 200d .',
 'cwst low day 4.50 , near high day 4.56 , watchn b/out , minim risk',
 'all : gme gamestop short target spi',
 'time get # cloud stock vmw cm',
 'bac keep overniight mmi po . bin premarket tmorrow .',
 'polk expect 2013 .s . new vehicl egistr 15.3 million - polk - f gm i think low',
 'veri bullish market also talk trend scti ost angi fio panw a jcp p yep mnst gpn show .',
 'bac happen next ?',
 'kcg someon bought 3.22k 4 jan 18 call ....',
 'man i didnt know skippi i made ... would thrown jar h # hormel',
 'big move bond today , 7 month high 10 rate , still go lower zn_f , could get truli ugli good nfp number am spi tt',
 'market wrap video + addit watch ist includ : bcei bji cee es son sqnm nx yep',
 'mayb vrng ask judg 7 % royalti becam riski goog deal ? want settl',
 'bji over 35.53 good volum',
 'cee over 35.12',
 'sqnm over 5.05',
 'nx on flag break',
 '3d system bring next-gen consum 3d print ce 2013 ddd',
 "aap top april aston kutcher star 'job ' . kinda like facebook 'social network ' came . fb",
 'vng w/ macd turn & signal line , vng could post nice ralli current level',
 'pi 3q 10q oper cash flow 9mo -20million . 269 % declin vs. 9mo year ago .',
 'bbbi 3q 10q oper cash flow 135 million . 53 increas vs. year ago q3 . 64 % improv q q',
 'di 6mo oper cash flow 267 million . increas 187 million vs.6mo year ago . 233 % increas',
 'am 3q 10q 9mo oper cash flow 32 million vs. neg 26 mil 9mo year ago .',
 '3q oper cash flow neg 16 million . vs. year ago 3q neg 68million . 52 million improv',
 'a quiet carl icahn = bullish . nfx short paranoid everi close get acquir . think aapl , msft , amzn , fb',
 'i aapl bull break trend line obv',
 "user phantom7 i 've call +4 ever sinc start thing . 3.75 given~ kcg",
 'nx watch list small flag volum 26 % ave full day good volum',
 'goog pois clear next resist ( buy / add area ) watch action / volum close',
 'gdp watch list slightli line 50-day ema light volum 5 % ave full day',
 'took profit ddd , add break 60 volum .',
 "chk - i 'm look - small risk posit call . scalp - mayb swing xe watch .",
 'onti if holder would hold rais ask , could realli pop . go climb slowli regardless ...',
 'eog pxd oa # energyswag',
 'aap move volum . couldnt cope descend trend line . trend still . perhap 460 imposs .',
 'aap 50ema continu work aap make lower high maco sens',
 'went short spi yesterday , pick aap instead . still think market need move bit resum move upsid .',
 'aap peopl realist . market undecid appl . earn lift cloud . if good might eay see revers .',
 'will watch close care decid whether ong shot aap . below 530 shot ! ! !',
 'jcp keep eye triangl . big short int , 34 % . report feb 27. cup & handl . dt . ong',
 'sold littl goog ... first time',
 'nice cup handl breakout mca',
 'faf new high .',
 "spi give aap finger . we n't care anymor lol",
 'the smith & corona ok. amzn',
 'va - ong 43.07 . trail stop 58.98 11 stop 54.53 , 52.45 , 48.05 , 47.32 , 46.71 , ... 41.32 & 39.57 -',
 "amzn alert updat : last minut push tri shake put . 're hang .",
 'aap volum higher today monday . keep mind .',
 'hb.a - ong 73.67 . trail stop 71.92 3 prior stop 70.86 , 68.64 62.41 -',
 'the key panic . aap domain twitchi day trader robot , long term hold fundament',
 'nvda 4 hour - love see vol explod .',
 'vng - take hard look goog ftc settlement patent . ftc make goog play nice vng ? make sens',
 'worri i gone oco 737.71 call goog ! door step nearli 40 move',
 'vng crazi anyon listen trade tool .',
 "goog get fuel aap 's revers .",
 'user make bbi offer shave 4 offer price ? bid went 24-26 20 matter month .',
 'nvda - answer question entri ( add ) red candl 10:50am today . ove flag',
 'aap 950 lot bid feb 580 call 9.50 , might push stock creat support . 26 delta option',
 'wpi - short candid list 12/31 miss , got start short today',
 'mye break',
 'short ht 200 sma stop high day . first target 53.95 . second target 53.21 gap fill .',
 'qcom introduc streamboost : averag home connect seven devic internet',
 'nvda love see momo next week like previou histogram bar note .',
 'hma unusu option activ . trader buy 11k jan 9 put . short term bear play',
 'adb option trader buy 5,300 feb 39c oi 741 . bet stock 39 feb 16th',
 'nvda ook bullish must stay 13.05 close basi ( monthli ) , ep say ?',
 'sqnm watch list line volum 86 % ave full day',
 'hott fail breakout ?',
 "zn_f tick .. i 'd seller sdjpi ( * i n't alreadi ) ...",
 'ino wow , nice accumul today , heavi ...',
 'znga fat juici short back lower level close gap 2.72 ?',
 'gdot nice bounc 50sma . ook readi test recent high',
 "hma ook 10 's ; head higher !",
 "spf ook 9 's , head higher lower rate .",
 'gs jpm xf hod , hungri stock ... spi',
 'chk weekli bullish engulf',
 'gs look good head next week .',
 'aap know ipad mini stock everywher . go 8 differ store none em stock',
 'as goog explod aapl implod mint 21 23 user vid year ago mark nail subject',
 'kkd krispi kreme doughnut , inc. ic xchang confer ( ive ) 01/17/13 9:15 a.m . et',
 'pick fs pullback due downgrad . held support close week . first pt 37.30',
 "user : i 've pick one , i 'm call kkd next food compani make dpz like run twenty13 .",
 'znga still show red dead enko view , pf box size 0.25',
 'gs enko view gs , pf box size = 5 show potenti break 175',
 'nvda enko view show red dead , need 14 long & less 13 short',
 'csx enko view , pf box size = 1 , vey bullish 21 , coal stock confirm move rail .',
 'goog and enko w/ pf box size 50 look like fail breakout',
 'user at 155 gs bullish fin rate low = the fed put !',
 'user znga i use lag indic lag stock ; )',
 'goog , i like close 744.96',
 'fs b/o bull flag heavi vol . etest support today light vol . 41 % short float',
 'msft gap close . continu base . si rise . nice : pickup w/ stop major support & 28.22 pt .',
 'financi continu rip . easi money . c approach 43 pt',
 "vs follow through . 10 dma cross 200 dma . trade ma 's . great setup",
 'user bac yeah ... made easi profit slash job , close win-win sale .',
 'new buy today watch list well nx 20 % son yep bcei gdp ay sqnm total trigger week 39 - big week',
 'sbx # si # earththi kind stuff make us perk ( sorri ! ) .but , go ... bullish five wave 58 .',
 'can say brainier ? ong sbac stock , 60/80 feb collar protect ...',
 'anyon say much svu would go even deal goe ? 4 ? 5 ? not sure much upsid left .',
 'nvda bounc continu stock clear 200sma 13 level . ong',
 'axti momentum pick w/ macd climbing/si rising.obv indic made new higher high week',
 'gdot obv move upward mean big money move stock slowli . ong',
 'aapl daili ( see note )',
 'amzn daili ( see note )',
 'c daili ( see note )',
 "egov long 16.62 strong ma 's , resting/bas , room upper bolli absorb 10/20 day atr",
 'aa fib friend',
 'tsa : judg dismiss massachusett state automobil dealer associ awsuit -',
 "bac trend n't appear slow yet . it 's prudent take profit time .",
 'fe - look like fire sell signal friday , may trade short tick friday low - work util later ...',
 'coh also got reject cloud still slight uptrend past . buy enter cloud',
 'yum look good cloud stop either 200 sma cloud . target 50 sma',
 'eqix exp fb gs hog mon pii qcom qih soda some idea next week . favorit setup eqix',
 'eqix no posit , would like see breakout 216.50 . prefer consolid though',
 'time contract aap.down test 500 week weds.long jan11th 510/500 put spread',
 'aap bounc come ?',
 'fs en fuego ! !',
 'axa over-sold oscil ang .... indic suggest buy price hold prev close + increas volum .',
 "a i 'm hold check . user : bullish macd cross : bbg cop eni eog jec ig sfi xe xop",
 'jd beauti trend , 13.5 bring dip buyer',
 'ko troubl stay 200 day sma past week . could short higher stop 38',
 'mako red day monday break support could test old low 9-9.25',
 'after-hour most advanc : opt mako fod gnmk jd ege amn px aay ddd sv pm bk f',
 'goog simpl fibonacci project close 739 . 127.2 % 766 161.8 % 802',
 'whi i buy aap monday -',
 'user : amzn 263 measur move 307',
 "user the ino pipelin partnership ni 's mk -- pretti much sum ...",
 'amzn data compani , retail . a new post .',
 "trade environ favor long side . do n't stay welcom . too qualiti leader . gs amh ocn egn hov aap",
 "aap amaz run sinc 2005 . i n't think 's .",
 'a tale two stock aap goog spi qqq',
 "f ford 's power bullish pattern dictat price direct",
 "dt - descend triangl . ower high . did n't particip well ralli & 's overbought .",
 'cva over 19.00',
 'mck over 100.05 -',
 'vmed know prefer 3-4 day pullback revers mayb mon tuesday flag break sup',
 'just kid , legibl version . current long fs ( tweet friday )',
 "ford perform well due hurrican sandi 's destruct . f palladium well pa bank buy pick bac c san gs",
 'gs buy pullback 133 bigger pullback 130 .',
 'ceg keep watch list .',
 'i wish tv would die alreadi like newspap told cb ftw !',
 'i think aap head back check 506 support',
 'amzn ..... yap yap yap',
 'sndk pattern look interest . can success break gap time around ?',
 '# amzn all-tim high pre-market , aapl still plung . interest trade day !',
 'see risk es_f 1442.00-1423.75 bearish momentum diverg resolv spx spi # stock .',
 'user : onxx strong price & vol expans friday . possibl look higher price > anoth biotech 2 level',
 'znga momentum build upside. ? on watch .',
 'es watch list also fast move today volum 77 % ave full day usual tini volum',
 'twi like long 24 % short ...',
 'green weekli triangl heo , .... pdate',
 'eog - 60 min pullback breakout - watch 1/2 posit',
 'kcg 3.75 ?',
 'zc almost hit stop loss ... glad see head back',
 'aap close short nice gain .',
 "v beauti uptrend sinc june '12 . never broke higher high , higher low trend",
 'the awesom aap trendlin ever . sinc 1986 ! !',
 'ddd - ong 27.95 . trail stop 42.35 7 prior stop 41.70 , 39.03 , 36.53 , 32.35 , 27.95 , 25.44 22.93 -',
 'nx largest watch list gainer new buy friday biggest mover today protect gain',
 'green weekli triangl kto , .... pdate',
 'ak correct - pphm largest watch list gainer today - though gap big open',
 "aap posit close 530 today bullish . i 'll look possibl ong set .",
 'ceg possibl ong today want play jpmogan biotech confer .',
 'fme : ong 10.25 . trail stop 13.75 8 prior stop 12.29 , 11.50 , 10.97 , 10.63 , 10.36 , ... 9.64 & 9.03 -',
 'i show ma friday upsid orang dot traget 517+ hit morn red dot',
 'to trigger 34 . first target 34.55-.90',
 'sxc - break key downward channel level . ike move much higher .',
 'must follow young man user : amzn data compani , retail . a new post .',
 'pg short back',
 'ovti downgrad sept 7th 16.77 q1 look good . next file q3 end feb .',
 'vs option trader sell 26k 47.25 - 52.25 call spread march . big bet stock 47.25 march expiri',
 'aa option trader bet bad earn sell 6,200 jan 9c buy 3,200 jan 9p . could hedg stock . both trade low oi',
 'skx q3 oper cash flow neg 60million . 80million declin vs.q3 2011',
 'skx 9 mo . 2012 oper cash flow neg 20 million . 95 million declin vs. 9mo 2011',
 'ed weekli triangl snss , ..... pdate',
 'bac avrg 12.127',
 'first trade come back vacat . hot short 59.80 . stop 60.30',
 'green weekli triangl scc , .... pdate',
 'podd break new 52wk high decent base',
 '3 horsemen high beta momo chase fs gmc nfx slam bit : advanc tell new year parti mrkt ?',
 'pna look like solid set',
 'name buy pullback gs ceg fb f',
 'ba flush',
 'amazon break 1,600 ( adjust split ) via user amzn',
 'financi xf drive mkt higher , today weak-ish ( except jpm ) 1st time , littl red flag 1 ...',
 'ive broadcast got long signal pcn cover discount buy-in ! need push',
 'amzn vome go , big boy grab stock . higher price come .',
 'twi high seen sinc septemb',
 'user gold 2011 stock contest w v , silver 2012 w tkc . will ddaif call win 2013 ?',
 'amzn fb pick higher price week . both break consider volum .',
 'eceryon want piec pcn gorwth magic ... stake high ... innov fast market stake high',
 "user scheplick it 's easi short amzn - buy ipad mini , tax prep book border ackspac time . ; - )",
 'might open posit s today . cup handl make one fli 7-7.5 quickli .',
 'cs , ko posit .... nice revers ko',
 'axp tri make move . get interest .',
 'ma strong follow thru day break new high last friday - confirm solid',
 'v new high , look higher price',
 'ceg strong breakout new high today 2x daili avg . volum . ook good upsid',
 'wetf cheap financi stock tri b/o . would like see pullback/consolid first',
 'nfx short paranoid everi close buyout come 1 night aapl , msft , goog , amzn , etc . domin webtv long nflx',

In [105]:
#applying count vectorization
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [123]:
x=cv.fit(stem_vec)

In [128]:
import pickle
with open("vectorizer.pickle","wb") as mdl_file:
    pickle.dump(x,mdl_file)

In [107]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5791, 8180))

In [108]:
y = df['Sentiment']

In [109]:
#importing multinomialnb from sklearn(naive_bayes)
from sklearn.naive_bayes import MultinomialNB

In [110]:
mb=MultinomialNB()

In [111]:
mb.fit(x,y)

MultinomialNB()

In [126]:
import pickle
with open("model.pickle","wb") as mdl_file:
    pickle.dump(mb,mdl_file)

In [112]:
df['Text'][3]

'MNTA Over 12.00  '

In [113]:
x[3]

array([1, 0, 0, ..., 0, 0, 0], shape=(8180,))

In [114]:
mb.predict([x[2]])

array([1])

In [115]:
[mb.predict([x[i]]) for i in range(len(x))]

[array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 ...]

In [116]:
# Define the mapping
label_map = {1: 'positive', -1: 'negative', 0: 'neutral'}

In [117]:

X_test = cv.transform(df)  # Convert text to numerical features
predicted_nums = mb.predict(X_test)  # Make predictions
predicted_labels = [label_map[num] for num in predicted_nums]  # Convert to labels

print(predicted_labels)

['negative', 'positive']

In [118]:
predicted_num = mb.predict([x[3]])[0]  # Extract the scalar value

# Convert to text label
predicted_label = label_map[predicted_num]

print(predicted_label)

positive

In [119]:
for row in x:
    predicted_num = mb.predict([row])[0]  # Predict using the entire row
    predicted_label = label_map[predicted_num]
    print(predicted_label)

positive
positive
positive
positive
positive
positive
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
positive
positive
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
positive
positive
negative
positive
positive
positive
negative
negative
negative
positive
negative
positive
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
negative
positive
negative
negative
positive
positive
positive
positive
negative
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
negative
positive
positive
positive
positive
negative
positive
positive
positive
positive
negative
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
negative
negative
positive
positive
negative
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
negative
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
negative
positive
positive
negative
positive
positive
positive
positive
negative
positive
positive
positive
positive
negative
positive
negative
negative
negative
negative
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
negative
negative
positive
negative
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
negative
positive
negative
negative
negative
negative
positive
negative
positive
negative
positive
positive
positive
negative
positive
positive
positive
negative
positive
negative
positive
positive
positive
positive
positive
positive
negative
positive
positive
negative
negative
positive
positive
negative
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
positive
negative
positive
positive
positive
positive
positive
negative
negative
negative
positive
negative
negative
positive
negative
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
negative
positive
negative
positive
positive
negative
negative
negative
negative
positive
positive
positive
positive
negative
negative
positive
positive
negative
positive
positive
positive
positive
positive
negative
negative
positive
positive
positive
negative
positive
positive
negative
positive
positive
positive
negative
negative
negative
positive
negative
positive
positive
positive
positive
positive
positive
negative
negative
positive
negative
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
negative
positive
negative
positive
positive
negative
negative
negative
positive
positive
positive
negative
negative
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
negative
negative
negative
negative
positive
positive
positive
positive
negative
positive
negative
positive
positive
negative
negative
negative
positive
positive
positive
negative
positive
positive
negative
positive
positive
positive
negative
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
negative
negative
positive
positive
positive
negative
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
negative
positive
negative
positive
negative
positive
positive
positive
negative
negative
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
negative
positive
positive
positive
positive
negative
positive
positive
positive
positive
negative
negative
positive
positive
positive
positive
negative
negative
positive
positive
negative
positive
negative
negative
positive
positive
negative
negative
positive
negative
negative
positive
negative
negative
positive
negative
positive
positive
positive
positive
negative
negative
negative
positive
positive
positive
positive
negative
positive
positive
positive
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
negative
positive
positive
negative
positive
negative
positive
negative
negative
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
negative
positive
positive
positive
negative
negative
negative
negative
positive
negative
positive
positive
negative
negative
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
negative
positive
negative
negative
positive
negative
positive
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
negative
positive
positive
negative
negative
positive
positive
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
negative
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
negative
positive
positive
negative
positive
positive
positive
positive
positive
negative
positive
positive
negative
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
negative
negative
positive
positive
positive
positive
positive
negative
positive
positive
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
negative
positive
negative
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
negative
positive
negative
negative
negative
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
negative
positive
positive
positive
positive
negative
positive
positive
positive
negative
positive
negative
positive
negative
negative
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
negative
positive
negative
positive
positive
positive
negative
negative
positive
positive
negative
positive
positive
negative
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
positive
positive
positive
positive
positive
negative
negative
positive
positive
negative
negative
negative
negative
positive
positive
positive
positive
negative
positive
positive
negative
negative
positive
negative
negative
positive
positive
positive
negative
positive
negative
positive
positive
negative
positive
negative
positive
positive
positive
positive
positive
negative
positive
negative
negative
positive
positive
positive
positive
positive
positive
negative
negative
negative
negative
negative
negative
negative
negative
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
negative
positive
negative
negative
negative
positive
negative
positive
positive
negative
positive
positive
positive
positive
negative
positive
negative
positive
negative
negative
negative
negative
negative
negative
positive
positive
positive
positive
negative
negative
positive
positive
negative
positive
positive
positive
positive
positive
positive
negative
negative
negative
negative
positive
negative
positive
negative
negative
positive
positive
positive
positive
positive
negative
negative
positive
positive
negative
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
negative
positive
positive
positive
positive
negative
negative
positive
positive
positive
positive
positive
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
negative
positive
positive
negative
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
negative
negative
negative
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
negative
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
negative
positive
positive
positive
negative
positive
positive
negative
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
negative
positive
negative
negative
positive
negative
positive
positive
positive
positive
positive
positive
positive
negative
negative
positive
positive
negative
positive
positive
negative
negative
positive
negative
positive
negative
negative
positive
positive
positive
positive
negative
negative
negative
negative
positive
negative
positive
positive
positive
negative
negative
positive
positive
positive
negative
positive
negative
positive
negative
positive
positive
negative
negative
negative
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
negative
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
negative
negative
negative
positive
negative
positive
positive
positive
positive
negative
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
negative
positive
positive
positive
positive
positive
negative
negative
positive
negative
negative
negative
positive
negative
negative
negative
positive
positive
positive
negative
positive
positive
positive
positive
negative
negative
positive
negative
negative
positive
negative
negative
positive
positive
negative
positive
positive
negative
positive
positive
positive
positive
positive
negative
negative
negative
positive
negative
negative
positive
positive
positive
negative
positive
positive
negative
positive
positive
positive
negative
positive
negative
positive
negative
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
negative
positive
negative
positive
negative
negative
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
negative
positive
positive
positive
negative
negative
negative
negative
negative
negative
positive
negative
negative
positive
positive
positive
negative
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
negative
negative
positive
negative
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
negative
negative
negative
positive
negative
negative
negative
negative
negative
positive
negative
positive
positive
positive
positive
positive
positive
negative
negative
negative
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
negative
negative
positive
positive
negative
positive
positive
positive
negative
positive
positive
positive
positive
negative
positive
positive
positive
positive
negative
negative
positive
positive
negative
negative
negative
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
negative
negative
positive
positive
positive
positive
negative
negative
negative
positive
positive
negative
positive
positive
negative
negative
positive
positive
positive
positive
negative
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
negative
negative
positive
negative
positive
positive
positive
positive
positive
positive
positive
negative
negative
positive
positive
negative
positive
positive
positive
negative
positive
positive
positive
negative
negative
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
negative
positive
negative
negative
positive
positive
positive
positive
negative
negative
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
negative
positive
negative
positive
positive
negative
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
negative
positive
negative
positive
positive
negative
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
negative
positive
positive
negative
positive
negative
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
negative
positive
negative
positive
negative
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
negative
negative
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
negative
positive
negative
negative
negative
positive
positive
positive
negative
positive
positive
negative
negative
negative
positive
positive
positive
negative
negative
negative
positive
negative
negative
positive
positive
positive
negative
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
positive
positive
positive
negative
negative
positive
positive
negative
positive
positive
positive
negative
negative
positive
positive
negative
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
positive
positive
negative
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
negative
positive
positive
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
negative
negative
positive
positive
negative
positive
negative
positive
positive
positive
positive
positive
negative
negative
negative
negative
positive
positive
positive
positive
positive
negative
positive
negative
negative
positive
positive
positive
positive
positive
negative
negative
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
negative

In [120]:
mb.score(x,y)

0.869797962355379

In [121]:

z=mb.predict(x)
pd.Series(z).value_counts()

 1    3921
-1    1870
Name: count, dtype: int64